const CURRICULUM = {
    "Anglais": [
        { "title": "Chapter 1: Tenses", "notions": [
            { "title": "1. The Simple Present", "type": "SP", "lessons": [
                { "title": "Uses", "content": `<h1>1. Uses - Simple Present</h1><div class="info-box"><strong>Contexte :</strong> En français, le présent sert à tout. En anglais, le Simple Present a des emplois précis et ne décrit jamais une action en cours.</div><h2>A. Les habitudes (Habits)</h2><p>On l'utilise pour parler d'actions qui se répètent régulièrement.</p><div class="def-box">I <strong>wash</strong> my hands every day.<br>He <strong>doesn't smoke</strong> anymore.</div><h2>B. Vérités scientifiques (Truths)</h2><p>Pour exprimer des faits qui sont toujours vrais.</p><div class="def-box">The heart <strong>pumps</strong> blood.<br>Water <strong>boils</strong> at 100 degrees.</div><h2>C. États permanents</h2><p>Pour parler de choses qui ne changent pas.</p><div class="def-box">He <strong>lives</strong> in Tessaoua.<br>She <strong>is</strong> a surgeon.</div><h2>D. Horaires fixes</h2><p>Pour les trains, les cours, les événements programmés.</p><div class="def-box">The biology class <strong>starts</strong> at 8 AM tomorrow.</div><h2>E. Instructions</h2><p>Les médecins ou les recettes l'utilisent pour donner des ordres.</p><div class="def-box">You <strong>take</strong> this medicine twice a day.</div>` },
                { "title": "Forms", "content": `<h1>2. Forms - Simple Present</h1><h2>A. Affirmative Form</h2><p>On ajoute la base verbale. À la 3ème personne (He/She/It), on ajoute <strong>-s</strong> ou <strong>-es</strong>.</p><table><tr><th>Sujet</th><th>Forme</th><th>Exemple</th></tr><tr><td>I/You/We/They</td><td>Base verbale</td><td>I work</td></tr><tr><td>He/She/It</td><td>Verbe + s/es</td><td>He works</td></tr></table><h3>Règles d'orthographe :</h3><ul><li>Cas général : On ajoute <strong>-s</strong>. (work ➔ works)</li><li>Verbes en -o, -ss, -sh, -ch, -x : On ajoute <strong>-es</strong>. (go ➔ goes, wash ➔ washes)</li><li>Verbes en consonne + y : Le "y" devient "i" + <strong>-es</strong>. (study ➔ studies)</li></ul><div class="warn-box"><strong>Exceptions :</strong> Have ➔ has. Be ➔ am/is/are. Do ➔ does.</div><h2>B. Negative Form</h2><div class="warn-box"><strong>⚠️ RÈGLE D'OR :</strong> Avec "doesn't", le verbe perd son "s" ! <em>Faux : He doesn't works.</em> <em>Vrai : He doesn't work.</em></div><h2>C. Interrogative Form</h2><div class="warn-box"><strong>⚠️ MÊME RÈGLE :</strong> Avec "Does", le verbe reste à la base verbale. <strong>Does</strong> he <strong>work</strong>?</div><h3>Wh- words</h3><p>What, Where, When, Who, Whom, Whose, Why, Which, How.</p>` },
                { "title": "Time Expressions", "content": `<h1>3. Time Expressions</h1><h2>A. Les adverbes de fréquence</h2><ul><li><strong>Always</strong> (toujours) - 100%</li><li><strong>Usually</strong> (habituellement) - 80%</li><li><strong>Often</strong> (souvent) - 70%</li><li><strong>Sometimes</strong> (parfois) - 50%</li><li><strong>Rarely</strong> (rarement) - 10%</li><li><strong>Never</strong> (jamais) - 0%</li></ul><div class="def-box"><strong>Règles de placement :</strong><br>1. <strong>Avant le verbe principal</strong> : The doctor always washes...<br>2. <strong>Après le verbe "Be"</strong> : The patient is always tired.</div><div class="warn-box"><strong>Cas particulier : Never et Rarely.</strong> Ils ont un sens négatif, on ne met pas "don't/doesn't" avec eux. <em>Vrai : He never smokes.</em></div><h2>B. Les expressions de fréquence</h2><p>Elles se placent à la fin de la phrase.</p><ul><li>Every day / Every morning</li><li>Once a day / Twice a week</li><li>On Mondays / At the weekend</li></ul>` }
            ]},
            { "title": "2. The Present Progressive", "type": "PP", "lessons": [
                { "title": "Uses", "content": `<h1>1. Uses - Present Progressive</h1><p>Le Present Progressive décrit une action dynamique, en train de se dérouler. C'est l'équivalent de "être en train de".</p><ul><li><strong>Actions happening right now</strong> : The doctor <strong>is examining</strong> the patient right now.</li><li><strong>Temporary situations</strong> : I <strong>am taking</strong> antibiotics this week.</li><li><strong>Changes and trends</strong> : The patient <strong>is feeling</strong> better every day.</li><li><strong>Future arrangements</strong> : We <strong>are visiting</strong> the clinic tomorrow.</li><li><strong>Annoying habits (avec always)</strong> : He <strong>is always coughing</strong>!</li></ul>` },
                { "title": "Forms", "content": `<h1>2. Forms - Present Progressive</h1><div class="def-box">Sujet + <strong>Be</strong> (am/is/are) + <strong>Verb + -ing</strong></div><p><strong>Règles d'orthographe (-ing) :</strong> -e muet ➔ -ing. -ie ➔ -ying. CVC ➔ double la consonne.</p><h3>Negative & Interrogative</h3><p>He <strong>isn't sleeping</strong>. / <strong>Are</strong> you <strong>feeling</strong> okay?</p>` },
                { "title": "Stative Verbs", "content": `<h1>3. Non-Progressive Verbs</h1><p>Ces verbes n'acceptent <strong>JAMAIS</strong> le Present Progressive.</p><ul><li><strong>Sentiments</strong> : love, like, hate, want.</li><li><strong>Pensée</strong> : know, believe, understand.</li><li><strong>Sens</strong> : see, hear, smell, taste.</li><li><strong>Possession</strong> : have (possess), own, belong.</li></ul><div class="warn-box"><strong>⚠️ LE PIÈGE :</strong><br>1. THINK : I <strong>think</strong> you are right (Opinion). / I <strong>am thinking</strong> (Réflexion).<br>2. HAVE : He <strong>has</strong> a headache (Possession). / He <strong>is having</strong> lunch (Action).</div>` },
                { "title": "Time Expressions", "content": `<h1>4. Time Expressions</h1><table><tr><th>Marqueur</th><th>Temps</th><th>Exemple</th></tr><tr><td>Every day</td><td>Simple Present</td><td>I take a pill every day.</td></tr><tr><td>Now</td><td>Present Progressive</td><td>I am taking a pill now.</td></tr></table>` }
            ]},
            { "title": "3. The Simple Past", "type": "Past", "lessons": [
                { "title": "Uses", "content": `<h1>1. Uses - Simple Past</h1><p>Le Simple Past sert à parler d'actions complètement terminées, sans lien avec le présent.</p><ul><li><strong>Completed actions</strong> : The doctor <strong>examined</strong> the patient yesterday.</li><li><strong>Past habits</strong> : I <strong>played</strong> football every day when I was young.</li><li><strong>Series of actions</strong> : He <strong>woke up</strong>, <strong>took</strong> a shower, and <strong>went</strong> to the hospital.</li></ul>` },
                { "title": "Forms", "content": `<h1>2. Forms - Simple Past</h1><h3>A. Affirmative (Regular)</h3><div class="def-box">Sujet + <strong>verb + ed</strong></div><p><strong>Règles :</strong> -e ➔ +d. Consonne+y ➔ ied. CVC ➔ double la consonne.</p><h3>B. Negative</h3><div class="warn-box"><strong>⚠️ RÈGLE D'OR :</strong> Avec "didn't", le verbe revient à sa forme de base ! <em>He didn't work.</em></div><h3>C. Interrogative</h3><p><strong>Did</strong> + sujet + base verbale ?</p>` },
                { "title": "Time Expressions", "content": `<h1>3. Time Expressions</h1><ul><li><strong>Yesterday</strong> (hier)</li><li><strong>Last night / Last week</strong></li><li><strong>Ago</strong> (il y a) : Ex: two days ago.</li><li><strong>In + année passée</strong> : in 2010.</li></ul>` },
                { "title": "Irregulars", "content": `<h1>4. Irregular Verbs</h1><div class="warn-box"><strong>⚠️ ATTENTION :</strong> La règle d'or s'applique toujours ! On utilise "did/didn't" et le verbe revient à sa BASE VERBALE.</div><table><tr><th>Base verbale</th><th>Simple Past</th></tr><tr><td>be</td><td>was / were</td></tr><tr><td>have</td><td>had</td></tr><tr><td>go</td><td>went</td></tr><tr><td>see</td><td>saw</td></tr><tr><td>take</td><td>took</td></tr></table>` }
            ]},
            { "title": "4. The Simple Future", "type": "Future", "lessons": [
                { "title": "Uses", "content": `<h1>1. Uses - Simple Future</h1><p>Il existe deux façons d'exprimer le futur : <strong>Will</strong> et <strong>Be going to</strong>.</p><h2>A. Will</h2><ul><li><strong>Spontaneous decisions</strong> : The patient is bleeding! I <strong>will call</strong> a doctor!</li><li><strong>Predictions</strong> : I think the surgery <strong>will be</strong> successful.</li><li><strong>Promises</strong> : I <strong>will help</strong> you.</li></ul><h2>B. Be going to</h2><ul><li><strong>Intentions</strong> : I <strong>am going to study</strong> medicine next year.</li><li><strong>Predictions based on evidence</strong> : Look at those clouds! It <strong>is going to rain</strong>.</li></ul>` },
                { "title": "Forms", "content": `<h1>2. Forms - Simple Future</h1><h2>A. With "Will"</h2><div class="def-box">Sujet + will + base verbale<br>Sujet + will not (won't) + base verbale<br>Will + sujet + base verbale ?</div><h2>B. With "Be going to"</h2><div class="def-box">Sujet + am/is/are + going to + base verbale</div>` },
                { "title": "Will vs Going to", "content": `<h1>3. Will vs Be going to</h1><table><tr><th>Contexte</th><th>Temps</th><th>Exemple</th></tr><tr><td>Décision spontanée</td><td>Will</td><td>"I'm cold." - "I <strong>will close</strong> the window."</td></tr><tr><td>Intention planifiée</td><td>Be going to</td><td>"I <strong>am going to close</strong> the window tonight."</td></tr><tr><td>Prédiction sans preuve</td><td>Will</td><td>"I think people <strong>will live</strong> on Mars."</td></tr><tr><td>Prédiction avec preuve</td><td>Be going to</td><td>"Look at the crash! He <strong>is going to die</strong>."</td></tr></table>` },
                { "title": "Time Expressions", "content": `<h1>4. Time Expressions</h1><ul><li><strong>Tomorrow</strong> (demain)</li><li><strong>Next week / Next month</strong></li><li><strong>Soon</strong> (bientôt)</li><li><strong>In + durée</strong> : The doctor <strong>will return</strong> in two hours.</li><li><strong>Tonight</strong> (ce soir)</li></ul>` }
            ]}
        ]}
    ]
};
