/**
 * 📚 ENRICHISSEUR LOCAL DE COURS (+1000%)
 *
 * Le contenu des cours vient de Firebase et peut être court. Ce service génère
 * LOCALEMENT (0 requête réseau, 100 % hors-ligne) des sections pédagogiques
 * supplémentaires et cohérentes avec le chapitre, portant la longueur perçue
 * du cours à ~10× :
 *   1. Objectifs du chapitre
 *   2. Méthode pas-à-pas
 *   3. Exemples résolus / Exemples d'application
 *   4. Erreurs fréquentes à éviter (pièges)
 *   5. Points clés à retenir
 *   6. Questions d'auto-évaluation
 *   7. Schéma annoté (si le chapitre s'y prête)
 *
 * Le contenu est adapté au thème détecté (mathématiques, analyse, géométrie,
 * trigonométrie, physique, chimie, SVT, probabilités, ...) pour rester pertinent.
 */

import { schemaPourChapitre } from "./schemas";

export interface SectionCours {
  emoji: string;
  titre: string;
  lignes: string[];
}

function normaliser(s: string): string {
  return (s || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9 ]/g, " ");
}

export type ThemeCours =
  | "mathematiques"
  | "analyse"
  | "geometrie"
  | "trigonometrie"
  | "complexes"
  | "probabilites"
  | "physique"
  | "chimie"
  | "svt"
  | "general";

export type NiveauScolaire = "6e" | "5e" | "4e" | "3e" | "2nde" | "1ere" | "terminale";

export function detecterTheme(titre: string, matiere?: string): ThemeCours {
  const t = normaliser(`${titre} ${matiere || ""}`);
  if (/ln|log|expo|derive|integr|limite|continu|suite|fonction/.test(t)) return "analyse";
  if (/angle|sin|cos|tan|trigonometr/.test(t)) return "trigonometrie";
  if (/complexe|imaginaire|argument|module/.test(t)) return "complexes";
  if (/probab|denombrement|arrangement|combinaison|loi|statist/.test(t)) return "probabilites";
  if (/vecteur|droite|plan|triangle|pythagore|cercle|sphere|aire|volume|projet/.test(t)) return "geometrie";
  if (/chimi|solution|mole|atom|reaction|electro|oxydo|acide|base|concentration/.test(t)) return "chimie";
  if (/physi|mecani|force|vitesse|energie|electric|mouvement|newton|magnet/.test(t)) return "physique";
  if (/svt|biologi|cellule|genetique|ecosystem|neurone|digest|reprodu|vegetal|adn/.test(t)) return "svt";
  if (/math|algebr|equat|nombre|calcul/.test(t)) return "mathematiques";
  return "general";
}

/**
 * Détecte le niveau scolaire à partir du titre du chapitre.
 * Ex: "Arithmétique - Terminale" → "terminale"
 *     "Fractions - 5e" → "5e"
 *     "Géométrie dans l'espace" → "3e" (défaut)
 */
export function detecterNiveau(titre: string): NiveauScolaire {
  const t = normaliser(titre);
  if (/terminale|terminale/.test(t)) return "terminale";
  if (/premiere|1ere/.test(t)) return "1ere";
  if (/seconde|2nde/.test(t)) return "2nde";
  if (/troisieme|3e/.test(t)) return "3e";
  if (/quatrieme|4e/.test(t)) return "4e";
  if (/cinquieme|5e/.test(t)) return "5e";
  if (/sixieme|6e/.test(t)) return "6e";
  // Défauts selon le thème
  if (/derive|exponentielle|logarithme|limite|continu|integrale|primitive/.test(t)) return "terminale";
  if (/probabilite|statistique/.test(t)) return "terminale";
  return "3e";
}

function majuscule(s: string): string {
  return s ? s.charAt(0).toUpperCase() + s.slice(1) : s;
}


 const GABARITS: Record<ThemeCours, {
  objectifs: string[];
  methodes: string[];
  exemples: string[];
  pieges: string[];
  cles: string[];
  autoEval: string[];
}> = {
  mathematiques: {
    objectifs: [
      "Connaitre la division euclidienne : a = bq + r avec 0 <= r < b (b non nul).",
      "Application : Determiner le quotient et le reste de 2026 par 17 (2026 = 17 x 119 + 3).",
      "Maitriser : Reconnaitre un nombre premier et decomposer un entier en produit de facteurs premiers.",
      "Connaitre les criteres de divisibilite par 2, 3, 5, 9 et 10 pour accelerer un calcul.",
      "Application : Calculer le PGCD de deux entiers par l'algorithme d'Euclide.",
      "Maitriser : Utiliser PGCD(a ; b) x PPCM(a ; b) = a x b pour trouver le PPCM.",
      "Application : Rendre une fraction irreductible en divisant numerateur et denominateur par leur PGCD.",
      "Connaitre la regle des signes et les priorites operatoires : parentheses, puissances, x et /, + et -.",
      "Maitriser : Calculer avec des puissances : a puissance m x a puissance n = a puissance (m+n).",
      "Application : Encadrer et comparer des nombres reels, utiliser la valeur absolue comme une distance.",
      "Maitriser : Simplifier une racine carree : racine(72) = 6 racine(2).",
      "Application : Rendre un denominateur rationnel : 1/racine(2) = racine(2)/2.",
      "Connaitre les trois identites remarquables : (a+b) carre, (a-b) carre et (a-b)(a+b).",
      "Application : Developper (2x + 5) carre = 4x carre + 20x + 25 sans erreur de signe.",
      "Maitriser : Factoriser par un facteur commun, puis par une identite remarquable.",
      "Application : Factoriser x carre - 9 = (x - 3)(x + 3).",
      "Maitriser : Resoudre une equation du premier degre ax + b = 0 (a non nul) : x = -b/a.",
      "Application : Resoudre une inequation du premier degre en changeant le sens quand on divise par un negatif.",
      "Maitriser : Etudier le signe d'un produit de facteurs avec un tableau de signes.",
      "Application : Resoudre (x - 1)(x + 3) <= 0 et donner l'ensemble des solutions.",
      "Maitriser : Resoudre une equation du second degre par le discriminant : D = b carre - 4ac.",
      "Application : Calculer les racines de x carre - 5x + 6 = 0 (D = 1, x = 2 ou x = 3).",
      "Connaitre les relations entre coefficients et racines : somme = -b/a et produit = c/a.",
      "Maitriser : Factoriser un trinome avec ses racines : ax carre + bx + c = a(x - x1)(x - x2).",
      "Application : Etudier le signe d'un trinome selon le signe de a et le discriminant.",
      "Maitriser : Resoudre un systeme de deux equations a deux inconnues par substitution ou combinaison.",
      "Application : Resoudre 2x + y = 7 et x - y = 2 (solution x = 3 et y = 1).",
      "Maitriser : Manipuler des fractions algebriques : addition, simplification, conditions d'existence.",
      "Application : Mettre un probleme concret en equation (ages, partages, melanges).",
      "Maitriser : Verifier une solution en la reinjectant dans l'enonce et conclure avec l'unite demandee.",
    ],
    methodes: [
      "1. Lire l'enonce et ecrire les donnees sous forme d'egalites avant tout calcul.",
      "2. Chercher d'abord une decomposition (facteurs premiers, PGCD) avant de calculer de force.",
      "3. Algorithme d'Euclide : divisions successives jusqu'a un reste nul ; le dernier reste non nul est le PGCD.",
      "4. Pour une fraction : factoriser numerateur et denominateur puis simplifier.",
      "5. Respecter les priorites operatoires et traiter les parentheses de l'interieur vers l'exterieur.",
      "6. Pour une equation : regrouper les inconnues a gauche et les nombres a droite.",
      "7. Pour une inequation : multiplier ou diviser par un negatif change le sens de l'inegalite.",
      "8. Pour un signe : dresser un tableau de signes avec une ligne par facteur.",
      "9. Pour un second degre : calculer D, discuter son signe, puis appliquer les formules des racines.",
      "10. Pour un systeme : additionner ou soustraire les equations pour eliminer une inconnue.",
      "11. Toujours preciser le domaine de validite (denominateur non nul, quantite sous la racine positive).",
      "12. Verifier le resultat par reinjection et rediger la conclusion avec l'unite.",
    ],
    exemples: [
      "Exemple 1 : PGCD(1071 ; 462) par Euclide : 1071 = 2 x 462 + 147 ; 462 = 3 x 147 + 21 ; 147 = 7 x 21 + 0, donc PGCD = 21.",
      "Exemple 2 : PPCM(12 ; 18) : PGCD = 6 donc PPCM = 12 x 18 / 6 = 36.",
      "Exemple 3 : 2026 = 2 x 1013 avec 1013 premier : 2026 n'est pas un carre parfait.",
      "Exemple 4 : 252/420 = (2 carre x 3 carre x 7)/(2 carre x 3 x 5 x 7) = 3/5.",
      "Exemple 5 : racine(50) + racine(18) = 5 racine(2) + 3 racine(2) = 8 racine(2).",
      "Exemple 6 : 1/(racine(5) - 2) = (racine(5) + 2)/((racine(5) - 2)(racine(5) + 2)) = racine(5) + 2.",
      "Exemple 7 : (3x - 4) carre = 9x carre - 24x + 16.",
      "Exemple 8 : x carre + 6x + 9 = (x + 3) carre.",
      "Exemple 9 : 4x carre - 25 = (2x - 5)(2x + 5).",
      "Exemple 10 : 3x - 7 = 0 donne x = 7/3.",
      "Exemple 11 : -2x + 5 > 1 donne -2x > -4 donc x < 2 (le sens change car on divise par -2).",
      "Exemple 12 : (x - 1)(x + 3) = 0 donne x = 1 ou x = -3.",
      "Exemple 13 : x carre - 5x + 6 = 0 : D = 25 - 24 = 1, donc x1 = 2 et x2 = 3.",
      "Exemple 14 : x carre + x + 1 = 0 : D = 1 - 4 = -3 < 0, aucune solution reelle.",
      "Exemple 15 : 2x + y = 7 et x - y = 2 : en additionnant, 3x = 9 donc x = 3 et y = 1.",
    ],
    pieges: [
      "Poser une division euclidienne avec un reste plus grand que le diviseur.",
      "Confondre PGCD et PPCM : le PGCD divise les deux nombres, le PPCM en est un multiple.",
      "Oublier que 1 n'est pas premier et que 2 est le seul nombre premier pair.",
      "Developper (a + b) carre en a carre + b carre : il manque le double produit 2ab.",
      "Changer le sens d'une inegalite en multipliant par un nombre positif.",
      "Diviser une inegalite par une expression qui peut etre negative sans etudier son signe.",
      "Oublier la condition d'existence avant de simplifier une fraction algebrique.",
      "Ecrire racine(a + b) = racine(a) + racine(b) : c'est faux.",
      "Confondre D et racine(D) dans la formule des racines.",
      "Croire qu'un trinome de discriminant negatif change de signe : il garde le signe de a.",
    ],
    cles: [
      "Division euclidienne : a = bq + r avec 0 <= r < b.",
      "PGCD(a ; b) x PPCM(a ; b) = a x b.",
      "(a + b) carre = a carre + 2ab + b carre ; (a - b) carre = a carre - 2ab + b carre ; (a - b)(a + b) = a carre - b carre.",
      "Equation du premier degre : ax + b = 0 donne x = -b/a (a non nul).",
      "Inegalite : multiplier ou diviser par un nombre negatif inverse le sens.",
      "Second degre : D = b carre - 4ac ; D > 0 deux racines, D = 0 une racine double, D < 0 aucune racine reelle.",
      "Racines : x = (-b +/- racine(D))/(2a) ; somme = -b/a et produit = c/a.",
      "Signe du trinome : signe de a a l'exterieur des racines, signe oppose a l'interieur.",
      "Systeme : eliminer une inconnue par combinaison lineaire des deux equations.",
      "Racines : racine(ab) = racine(a) x racine(b) pour a et b positifs, mais racine(a + b) n'est pas racine(a) + racine(b).",
    ],
    autoEval: [
      "Calculer le PGCD et le PPCM de 84 et 126.",
      "Decomposer 3600 en produit de facteurs premiers.",
      "Calculer 3/(racine(3) - 1) en rendant le denominateur rationnel.",
      "Developper puis reduire (5x - 2) carre - (x + 3)(x - 3).",
      "Factoriser 9x carre - 12x + 4.",
      "Resoudre (2x - 5)(x + 4) = 0 puis etudier le signe du produit.",
      "Resoudre 5 - 3x <= 2x + 20.",
      "Resoudre 2x carre - 7x + 3 = 0 puis factoriser le trinome.",
      "Resoudre le systeme 3x - y = 5 et x + 2y = 4.",
      "Un pere a le triple de l'age de son fils ; dans 12 ans il n'aura plus que le double. Calculer leurs ages.",
    ],
  },
  geometrie: {
    objectifs: [
      "Connaitre les figures de base et leur codage : triangle, parallelogramme, cercle et droites remarquables.",
      "Application : Reconnaitre un triangle rectangle et identifier son hypotenuse.",
      "Maitriser : Appliquer le theoreme de Pythagore : dans un triangle rectangle, BC carre = AB carre + AC carre.",
      "Application : Utiliser la reciproque de Pythagore pour demontrer qu'un triangle est rectangle.",
      "Application : Utiliser le theoreme de Thales et sa reciproque pour calculer une longueur ou prouver un parallelisme.",
      "Maitriser : Calculer le perimetre et l'aire des figures usuelles (rectangle, triangle, disque).",
      "Connaitre les unites d'aire et de volume et les convertir (1 m carre = 100 dm carre).",
      "Application : Calculer le volume d'un pave, d'un cylindre, d'un cone et d'une sphere.",
      "Maitriser : Utiliser cos, sin et tan dans un triangle rectangle pour calculer un cote ou un angle.",
      "Connaitre les angles : complementaires, supplementaires, alternes-internes et correspondants.",
      "Application : Exploiter la propriete des angles inscrits : un angle inscrit vaut la moitie de l'angle au centre.",
      "Maitriser : Determiner le centre du cercle circonscrit a un triangle rectangle (milieu de l'hypotenuse).",
      "Connaitre la colinearite de deux vecteurs : u = k v.",
      "Application : Calculer les coordonnees d'un vecteur, d'une somme et d'un produit par un scalaire.",
      "Maitriser : Calculer une distance avec les coordonnees : AB = racine((xB - xA) carre + (yB - yA) carre).",
      "Application : Determiner les coordonnees du milieu d'un segment et d'un point de partage.",
      "Maitriser : Etudier l'alignement de trois points par la colinearite des vecteurs.",
      "Application : Determiner une equation de droite : y = mx + p ou ax + by + c = 0.",
      "Maitriser : Reconnaitre des droites paralleles (memes coefficients directeurs) ou perpendiculaires (produit egal a -1).",
      "Application : Calculer les coordonnees du point d'intersection de deux droites.",
      "Maitriser : Utiliser le produit scalaire : u . v = xx' + yy'.",
      "Application : Demontrer l'orthogonalite de deux droites par un produit scalaire nul.",
      "Application : Caracteriser un triangle rectangle, isocele ou equilateral avec les distances et le produit scalaire.",
      "Maitriser : Calculer l'aire d'un triangle avec les coordonnees ou avec (1/2)bc sin A.",
      "Connaitre les transformations : translation, symetries axiale et centrale, rotation et homothetie.",
      "Application : Determiner l'image d'une figure par une transformation et les proprietes conservees.",
      "Maitriser : Utiliser l'equation d'un cercle : (x - a) carre + (y - b) carre = R carre.",
      "Application : Reconnaitre une conique (parabole, ellipse, hyperbole) a partir de son equation.",
      "Maitriser : Calculer des longueurs, aires et volumes dans l'espace (droites et plans orthogonaux).",
      "Application : Resoudre un probleme de synthese en combinant Pythagore, Thales, vecteurs et produit scalaire.",
    ],
    methodes: [
      "1. Faire une figure a main levee et coder les donnees : c'est la moitie du travail.",
      "2. Identifier la nature de la figure (triangle rectangle, parallelogramme, cercle) avant de choisir un theoreme.",
      "3. Pour une longueur inconnue : Pythagore dans un triangle rectangle, Thales en presence de droites paralleles.",
      "4. Pour un parallelisme : reciproque de Thales ; pour un angle droit : reciproque de Pythagore.",
      "5. Pour un angle : choisir cos, sin ou tan selon les cotes connus (adjacent, oppose, hypotenuse).",
      "6. Pour des coordonnees : ecrire les formules de distance, de milieu et de vecteur avant de calculer.",
      "7. Pour un alignement : montrer que deux vecteurs sont colineaires (determinant nul).",
      "8. Pour une equation de droite : chercher deux points ou le coefficient directeur et l'ordonnee a l'origine.",
      "9. Pour une perpendicularite : verifier que le produit scalaire des vecteurs directeurs est nul.",
      "10. Pour une transformation : detailler l'image d'un sommet, puis conclure pour toute la figure.",
      "11. Pour un volume : ecrire la formule, remplacer par les valeurs et verifier l'unite (cm cube, m cube).",
      "12. Rediger la conclusion en citant la propriete utilisee et l'unite de la longueur, de l'aire ou du volume.",
    ],
    exemples: [
      "Exemple 1 : triangle rectangle avec AB = 3 cm et AC = 4 cm : BC = racine(9 + 16) = 5 cm.",
      "Exemple 2 : triangle de cotes 6, 8 et 10 : 10 carre = 100 et 6 carre + 8 carre = 100, donc il est rectangle.",
      "Exemple 3 : Thales avec AM/AB = AN/AC : AB = 6, AM = 2 et AC = 9 donnent AN = 3.",
      "Exemple 4 : perimetre d'un disque de rayon 7 cm : 2 x pi x 7 = 43,98 cm.",
      "Exemple 5 : aire d'un triangle de base 10 cm et de hauteur 6 cm : (10 x 6)/2 = 30 cm carre.",
      "Exemple 6 : volume d'un cylindre de rayon 3 cm et de hauteur 10 cm : pi x 9 x 10 = 282,7 cm cube.",
      "Exemple 7 : volume d'une sphere de rayon 3 cm : (4/3) x pi x 27 = 113,1 cm cube.",
      "Exemple 8 : tan(35 degres) = 0,70 donc la hauteur vaut 12 x 0,70 = 8,4 m.",
      "Exemple 9 : A(2 ; 3) et B(5 ; 7) : AB = racine(9 + 16) = 5.",
      "Exemple 10 : milieu de A(1 ; 4) et B(5 ; 2) : I(3 ; 3).",
      "Exemple 11 : droite passant par A(0 ; 2) et B(2 ; 6) : m = 2 et p = 2, donc y = 2x + 2.",
      "Exemple 12 : les droites y = 3x + 1 et y = 3x - 4 sont paralleles (meme coefficient directeur).",
      "Exemple 13 : u(2 ; -1) et v(1 ; 2) : u . v = 2 - 2 = 0 donc les vecteurs sont orthogonaux.",
      "Exemple 14 : cercle de centre I(2 ; -1) et de rayon 3 : (x - 2) carre + (y + 1) carre = 9.",
      "Exemple 15 : une homothetie de centre O et de rapport 2 multiplie les longueurs par 2 et les aires par 4.",
    ],
    pieges: [
      "Confondre l'hypotenuse avec un cote de l'angle droit dans Pythagore.",
      "Utiliser Pythagore dans un triangle qui n'est pas rectangle.",
      "Oublier que Thales exige deux droites paralleles ET des points alignes.",
      "Confondre la reciproque d'un theoreme avec sa contraposée.",
      "Utiliser le cosinus avec le cote oppose : cos = adjacent / hypotenuse.",
      "Melanger degres et radians dans les fonctions trigonometriques de la calculatrice.",
      "Ecrire AB = (xB - xA) carre + (yB - yA) carre : la distance est la racine carree.",
      "Confondre coefficient directeur et ordonnee a l'origine dans y = mx + p.",
      "Se fier a la figure : elle n'est jamais une preuve, un angle droit se demontre.",
      "Oublier l'unite ou confondre aire et volume : un volume s'exprime en unite cube.",
    ],
    cles: [
      "Pythagore : dans un triangle rectangle, le carre de l'hypotenuse est la somme des carres des deux autres cotes.",
      "Reciproque de Pythagore : l'egalite demontre l'angle droit.",
      "Thales : des droites paralleles donnent des rapports de longueurs egaux.",
      "cos = adjacent/hypotenuse ; sin = oppose/hypotenuse ; tan = oppose/adjacent.",
      "Distance : AB = racine((xB - xA) carre + (yB - yA) carre) ; milieu : ((xA + xB)/2 ; (yA + yB)/2).",
      "Vecteurs colineaires : u = k v, equivalent a xy' - x'y = 0.",
      "Droites perpendiculaires : produit des coefficients directeurs egal a -1, ou produit scalaire nul.",
      "Produit scalaire : u . v = xx' + yy' = |u| x |v| x cos theta.",
      "Cercle : (x - a) carre + (y - b) carre = R carre (centre et rayon se lisent directement).",
      "Aires et volumes : les formules usuelles se combinent avec Pythagore dans l'espace.",
    ],
    autoEval: [
      "Un triangle a pour cotes 9 cm, 12 cm et 15 cm : est-il rectangle ? Justifier.",
      "Calculer la diagonale d'un rectangle de 6 cm sur 8 cm.",
      "Un cone a un rayon de 4 cm et une hauteur de 9 cm : calculer son volume.",
      "Calculer cos(60 degres) et en deduire l'hypotenuse si le cote adjacent mesure 5 cm.",
      "A(1 ; 1), B(4 ; 5) et C(7 ; 9) sont-ils alignes ? Justifier avec les vecteurs.",
      "Determiner l'equation de la droite passant par A(1 ; 3) et B(3 ; 7).",
      "Les droites y = -2x + 1 et y = 0,5x + 3 sont-elles perpendiculaires ?",
      "Determiner le centre et le rayon du cercle x carre + y carre - 4x + 6y - 12 = 0.",
      "Calculer l'aire d'un triangle dont deux cotes mesurent 7 cm et 9 cm et forment un angle de 30 degres.",
      "Une homothetie de rapport -1 : quelle transformation reconnait-on et que devient une aire ?",
    ],
  },
  analyse: {
    objectifs: [
      "Connaitre la notion de limite : comportement de f(x) quand x tend vers a ou vers l'infini.",
      "Application : Lever une forme indeterminee par factorisation, conjugaison ou terme dominant.",
      "Maitriser : Etudier la continuite d'une fonction en un point : limite egale a la valeur de la fonction.",
      "Application : Appliquer le theoreme des valeurs intermediaires pour justifier l'existence d'une solution.",
      "Connaitre la definition du nombre derive : f'(a) est la limite de (f(a+h) - f(a))/h quand h tend vers 0.",
      "Application : Interpreter f'(a) comme le coefficient directeur de la tangente en a.",
      "Maitriser : Calculer les derivees des fonctions usuelles (x puissance n, racine carree, 1/x).",
      "Application : Deriver un produit, un quotient et une composee (u v, u/v, u o v).",
      "Maitriser : Etudier le signe de f' pour dresser le tableau de variations.",
      "Application : Determiner les extremums locaux d'une fonction et les interpreter.",
      "Maitriser : Ecrire l'equation de la tangente : y = f'(a)(x - a) + f(a).",
      "Connaitre la fonction exponentielle : strictement croissante, toujours positive et e puissance 0 = 1.",
      "Application : Utiliser e puissance (a+b) = e puissance a x e puissance b.",
      "Maitriser : Resoudre une equation avec exponentielle en isolant e puissance x puis en utilisant ln.",
      "Connaitre la fonction logarithme neperien : definie sur les positifs et ln(ab) = ln a + ln b.",
      "Maitriser : Utiliser ln(e puissance x) = x et e puissance (ln x) = x pour x positif.",
      "Application : Resoudre une equation ou une inequation avec ln en respectant le domaine.",
      "Connaitre les suites : arithmetique (u(n+1) = u(n) + r) et geometrique (u(n+1) = q x u(n)).",
      "Application : Calculer le terme general : u(n) = u(0) + n r ou u(n) = u(0) x q puissance n.",
      "Maitriser : Calculer la somme des termes d'une suite arithmetique ou geometrique.",
      "Application : Etudier le sens de variation d'une suite (difference u(n+1) - u(n) ou quotient).",
      "Maitriser : Determiner la limite d'une suite geometrique selon la valeur de sa raison q.",
      "Application : Demontrer par recurrence une propriete dependant de l'entier n.",
      "Connaitre la notion de primitive : F'(x) = f(x).",
      "Maitriser : Calculer les primitives des fonctions usuelles et utiliser la linearite.",
      "Application : Calculer une integrale avec le theoreme fondamental : integrale de a a b de f = F(b) - F(a).",
      "Maitriser : Interpreter une integrale comme l'aire sous la courbe, avec son signe.",
      "Application : Calculer l'aire entre deux courbes en integrant la difference.",
      "Maitriser : Etudier une fonction complete : domaine, limites, derivee, tableau de variations, courbe.",
      "Application : Resoudre un probleme d'optimisation avec la derivee et le tableau de variations.",
    ],
    methodes: [
      "1. Toujours commencer par le domaine de definition : il conditionne tout le reste.",
      "2. Pour une limite : remplacer, et si la forme est indeterminee, factoriser, conjuguer ou utiliser le terme dominant.",
      "3. Pour une derivee : identifier la forme (somme, produit, quotient, composee) avant de deriver.",
      "4. Pour un tableau de variations : calculer f', resoudre f'(x) = 0, puis etudier le signe de f'.",
      "5. Pour une tangente : calculer f(a) et f'(a), puis ecrire y = f'(a)(x - a) + f(a).",
      "6. Pour une equation avec ln ou exp : isoler, puis utiliser la bijection reciproque en respectant le domaine.",
      "7. Pour une suite : calculer les premiers termes afin de conjecturer, puis demontrer.",
      "8. Pour une somme de suite : identifier la nature (arithmetique ou geometrique) avant d'appliquer la formule.",
      "9. Pour une recurrence : verifier l'initialisation, puis demontrer l'heredite avec l'hypothese au rang n.",
      "10. Pour une primitive : reconnaitre la forme usuelle et ne jamais oublier la constante.",
      "11. Pour une integrale : chercher une primitive, puis calculer F(b) - F(a).",
      "12. Conclure par une phrase : variations, extremum, aire ou resultat demande par l'enonce.",
    ],
    exemples: [
      "Exemple 1 : limite en l'infini de (3x + 1)/(x - 2) : en factorisant par x, la limite vaut 3.",
      "Exemple 2 : derivee de f(x) = x puissance 3 - 5x : f'(x) = 3x carre - 5.",
      "Exemple 3 : derivee de f(x) = (2x + 1)(x - 3) : f'(x) = 2(x - 3) + (2x + 1) = 4x - 5.",
      "Exemple 4 : derivee de f(x) = (x + 1)/x : f'(x) = (x - (x + 1))/x carre = -1/x carre.",
      "Exemple 5 : f(x) = x carre - 4x + 1 : f'(x) = 2x - 4 s'annule en 2, minimum f(2) = -3.",
      "Exemple 6 : tangente a f(x) = x carre en a = 3 : y = 6(x - 3) + 9, soit y = 6x - 9.",
      "Exemple 7 : suite arithmetique u(0) = 5 et r = -2 : u(10) = 5 - 20 = -15.",
      "Exemple 8 : suite geometrique u(0) = 3 et q = 2 : u(6) = 3 x 64 = 192.",
      "Exemple 9 : somme des 20 premiers entiers naturels : 20 x 21 / 2 = 210.",
      "Exemple 10 : somme 1 + 1/2 + 1/4 + ... : suite geometrique de raison 1/2, la limite de la somme vaut 2.",
      "Exemple 11 : e puissance x = 5 donne x = ln 5 = 1,609.",
      "Exemple 12 : ln(x - 1) = 0 donne x - 1 = 1 donc x = 2 (domaine x > 1 respecte).",
      "Exemple 13 : primitive de f(x) = 3x carre : F(x) = x puissance 3 + C.",
      "Exemple 14 : integrale de 0 a 2 de x dx = x carre/2, donc 4/2 - 0 = 2.",
      "Exemple 15 : aire entre y = x et y = x carre pour x entre 0 et 1 : integrale de (x - x carre) = 1/2 - 1/3 = 1/6.",
    ],
    pieges: [
      "Calculer une limite en remplacant alors que la forme est indeterminee (0/0 ou infini/infini).",
      "Oublier de verifier le domaine avant de resoudre une equation avec ln ou une racine carree.",
      "Confondre f'(a) et f(a) dans l'equation de la tangente.",
      "Deriver un produit en multipliant les derivees : il faut u'v + uv'.",
      "Oublier le signe dans la derivee d'un quotient : (u'v - uv')/v carre.",
      "Confondre suite arithmetique et suite geometrique (addition de r contre multiplication par q).",
      "Utiliser une formule de somme sans verifier la nature de la suite.",
      "Oublier la constante dans le calcul d'une primitive (sauf pour une integrale definie).",
      "Inverser les bornes d'une integrale : l'integrale change de signe.",
      "Conclure sur les variations sans etudier le signe de f' : le signe de f' n'est pas celui de f.",
    ],
    cles: [
      "Formes indeterminees : 0/0, infini/infini, 0 x infini, infini - infini : factoriser ou prendre le terme dominant.",
      "Nombre derive : f'(a) est la pente de la tangente a la courbe au point d'abscisse a.",
      "(u v)' = u'v + uv' et (u/v)' = (u'v - uv')/v carre.",
      "f' > 0 : f croissante ; f' < 0 : f decroissante ; f'(a) = 0 avec changement de signe : extremum.",
      "Tangente : y = f'(a)(x - a) + f(a).",
      "e puissance x toujours positif et strictement croissant ; ln est defini sur les positifs seulement.",
      "ln(ab) = ln a + ln b ; ln(a/b) = ln a - ln b ; ln(a puissance n) = n ln a.",
      "Suite arithmetique : u(n) = u(0) + n r et somme = nombre de termes x (premier + dernier)/2.",
      "Suite geometrique : u(n) = u(0) x q puissance n et somme = premier x (1 - q puissance n)/(1 - q) pour q different de 1.",
      "Integrale de a a b de f = F(b) - F(a) : elle mesure l'aire algebrique sous la courbe.",
    ],
    autoEval: [
      "Calculer la limite en l'infini de (2x carre + 1)/(x carre - 3).",
      "Deriver f(x) = (3x - 1)/(x + 2).",
      "Dresser le tableau de variations de f(x) = x puissance 3 - 3x.",
      "Determiner l'equation de la tangente a la courbe de f(x) = racine(x) en a = 4.",
      "Justifier que l'equation x puissance 3 + x - 1 = 0 admet une solution entre 0 et 1.",
      "Resoudre e puissance (2x) = 7.",
      "Resoudre ln(x + 2) < 1 en precisant le domaine.",
      "Calculer la somme des 15 premiers termes de la suite arithmetique de premier terme 4 et de raison 3.",
      "Etudier la monotonie de la suite definie par u(n) = (n + 1)/n.",
      "Calculer l'integrale de 1 a 3 de (2x + 1) dx.",
    ],
  },
  trigonometrie: {
    objectifs: [
      "Connaitre le cercle trigonometrique : cos x = abscisse de M, sin x = ordonnee de M, M point du cercle de rayon 1.",
      "Application : Placer un angle sur le cercle et lire cos x et sin x (ex : cos(pi/3) = 1/2, sin(pi/3) = racine(3)/2).",
      "Maitriser : Convertir degres et radians : 180 degres = pi rad ; 90 degres = pi/2 ; 60 degres = pi/3 ; 45 degres = pi/4 ; 30 degres = pi/6.",
      "Connaitre les valeurs remarquables : cos(0) = 1, cos(pi/6) = racine(3)/2, cos(pi/4) = racine(2)/2, cos(pi/3) = 1/2, cos(pi/2) = 0.",
      "Application : Utiliser sin carre(x) + cos carre(x) = 1 pour retrouver une valeur manquante (ex : cos x = 3/5 implique sin x = 4/5 ou -4/5 selon le quadrant).",
      "Maitriser : Appliquer les formules d addition : cos(a-b) = cos a cos b + sin a sin b ; sin(a+b) = sin a cos b + cos a sin b.",
      "Resoudre cos x = a sur [0 ; 2pi[ : si a = 1/2 alors x = pi/3 ou x = 5pi/3 (symetrie par rapport a l axe des abscisses).",
      "Application : Resoudre sin x = a sur R : x = alpha + 2k pi ou x = pi - alpha + 2k pi, k entier relatif.",
      "Maitriser : Resoudre les inequations trigonometriques sur un intervalle par lecture graphique sur le cercle.",
      "Connaitre les formules de duplication : cos(2a) = 2cos carre(a) - 1 = 1 - 2sin carre(a) ; sin(2a) = 2 sin a cos a.",
      "Application : Lineariser cos carre(x) = (1 + cos(2x))/2 pour integrer ou simplifier une expression.",
      "Maitriser : Determiner la periode de f(x) = A sin(omega x + phi) : T = 2pi / |omega|.",
      "Etudier les variations de sin et cos sur [0 ; 2pi] et tracer leurs courbes representatives.",
      "Application : Resoudre un triangle avec la loi des sinus a/sin A = b/sin B = 2R et Al-Kashi a carre = b carre + c carre - 2bc cos A.",
      "Maitriser : Calculer une aire avec la formule (1/2)bc sin A.",
    ],
    methodes: [
      "1. Convertir l angle dans l unite demandee (degres ou radians) avant tout calcul.",
      "2. Placer l angle sur le cercle trigonometrique et reperer le quadrant (signe de cos et sin).",
      "3. Appliquer la formule adaptee : Pythagore trigonometrique, addition, duplication ou linearisation.",
      "4. Pour cos x = a : ecrire les deux familles de solutions avec + 2k pi.",
      "5. Pour sin x = a : ecrire x = alpha + 2k pi OU x = pi - alpha + 2k pi.",
      "6. Restreindre les solutions a l intervalle demande en testant k = -1, 0, 1.",
      "7. Pour une inequation : hachurer la zone du cercle et lire l intervalle de x.",
      "8. Verifier chaque solution en la reinjectant dans l equation de depart.",
      "9. Pour un triangle : identifier les donnees puis choisir loi des sinus ou Al-Kashi.",
      "10. Rediger avec les unites : radians pour les angles calcules.",
      "11. Pour A sin(omega x + phi) : calculer amplitude |A| et periode 2pi/|omega|, puis tableau de variations.",
      "12. Relire : sur [0 ; 2pi[, cos x = a admet 0, 1 ou 2 solutions selon a.",
    ],
    exemples: [
      "Exemple 1 : Resoudre cos x = racine(2)/2 sur [0 ; 2pi[. Le cercle donne x = pi/4 ou x = 7pi/4.",
      "Exemple 2 : Resoudre sin x = -1/2 sur R. alpha = -pi/6. Solutions : x = -pi/6 + 2k pi ou x = 7pi/6 + 2k pi.",
      "Exemple 3 : cos x = 3/5 avec x dans [pi ; 2pi] (sin negatif). sin x = -racine(1 - 9/25) = -4/5.",
      "Exemple 4 : cos(pi/12) par duplication inversee : cos carre(pi/12) = (2 + racine(3))/4, donc cos(pi/12) = racine(2 + racine(3))/2.",
      "Exemple 5 : Integrale de sin carre sur [0 ; pi] : sin carre(x) = (1 - cos(2x))/2, primitive x/2 - sin(2x)/4, valeur pi/2.",
      "Exemple 6 : Triangle AB = 5, AC = 7, angle A = 60 degres. BC carre = 25 + 49 - 2*5*7*0,5 = 39. Donc BC = racine(39) = 6,24.",
      "Exemple 7 : Aire avec b = 8, c = 5, angle A = 30 degres : Aire = 0,5*8*5*0,5 = 10.",
      "Exemple 8 : Periode de f(x) = 3 sin(2x + pi/3) : T = 2pi/2 = pi. Amplitude 3.",
      "Exemple 9 : Resoudre cos(2x) = 0 sur [0 ; pi[. Poser X = 2x : X = pi/2 ou 3pi/2, donc x = pi/4 ou 3pi/4.",
      "Exemple 10 : sin(pi/2 - x) = cos x par la formule sin(a - b) avec a = pi/2.",
      "Exemple 11 : cos(a + b) + cos(a - b) = 2 cos a cos b (formule de Simpson).",
      "Exemple 12 : Triangle A = 50 degres, B = 60 degres, a = 10. b = 10*sin(60)/sin(50) = 11,3.",
      "Exemple 13 : cos x >= 1/2 sur [0 ; 2pi] : x dans [0 ; pi/3] union [5pi/3 ; 2pi].",
      "Exemple 14 : tan x = sin x / cos x, definie pour x different de pi/2 + k pi.",
      "Exemple 15 : cos(3pi/4) = -racine(2)/2, sin(3pi/4) = +racine(2)/2.",
    ],
    pieges: [
      "Confondre degres et radians : verifier le mode de la calculatrice avant chaque calcul.",
      "Oublier la 2e famille de solutions pour cos x = a : toujours deux familles avec + 2k pi.",
      "Pour sin x = a : la 2e famille est pi - alpha (pas -alpha).",
      "sin carre + cos carre = 1 donne sin x = +/- racine : le signe depend du quadrant.",
      "cos(2a) = 2cos carre(a) - 1 et NON 2cos(a) : ne jamais oublier le carre.",
      "Loi des sinus : penser a l angle obtus supplementaire (cas ambigu, deux triangles possibles).",
      "Al-Kashi : ne pas oublier le signe moins devant 2bc cos A.",
      "Periode de sin(omega x) : T = 2pi/|omega|, pas 2pi.",
      "tan x n existe pas en pi/2 + k pi (division par zero).",
      "Inequation trigonometrique sans le cercle : on rate toujours une borne. Toujours dessiner.",
    ],
    cles: [
      "Cercle trigo : M(x) = (cos x ; sin x), rayon 1, sens direct.",
      "180 degres = pi rad. Valeurs pi/6, pi/4, pi/3, pi/2 par coeur.",
      "sin carre + cos carre = 1.",
      "cos(a-b) = cos a cos b + sin a sin b ; sin(a+b) = sin a cos b + cos a sin b.",
      "cos(2a) = 2cos carre - 1 = 1 - 2sin carre ; sin(2a) = 2 sin a cos a.",
      "cos x = a : deux familles. sin x = a : alpha et pi - alpha.",
      "Periode de A sin(omega x + phi) : T = 2pi/|omega|.",
      "Loi des sinus : a/sin A = b/sin B = 2R. Al-Kashi : a carre = b carre + c carre - 2bc cos A.",
      "Aire = (1/2)bc sin A.",
      "Toujours verifier le mode degres/radians de la calculatrice.",
    ],
    autoEval: [
      "Convertir 135 degres en radians.",
      "Placer 5pi/6 sur le cercle et donner cos et sin.",
      "Resoudre cos x = -1/2 sur [0 ; 2pi[.",
      "Resoudre sin x = racine(3)/2 sur R.",
      "Sachant cos x = -3/5 avec x dans [pi/2 ; pi], calculer sin x.",
      "Lineariser cos carre(3x).",
      "Quelle est la periode de f(x) = 2 cos(x/2) ?",
      "Triangle : b = 6, c = 8, angle A = 45 degres. Calculer a.",
      "Resoudre sin x >= 1/2 sur [0 ; 2pi].",
      "Demontrer que cos(pi/2 - x) = sin x.",
    ],
  },

  probabilites: {
    objectifs: [
      "Connaitre le vocabulaire : experience aleatoire, univers, evenement et evenement contraire.",
      "Application : Decrire l'univers d'un lancer de deux des (36 issues equiprobables).",
      "Maitriser : Calculer une probabilite en situation d'equiprobabilite : cas favorables / cas possibles.",
      "Application : Determiner la probabilite d'un evenement contraire : p(A barre) = 1 - p(A).",
      "Maitriser : Calculer la probabilite d'une reunion : p(A union B) = p(A) + p(B) - p(A inter B).",
      "Application : Reconnaitre deux evenements incompatibles ou contraires.",
      "Connaitre les techniques de denombrement : factorielle, arrangements et combinaisons.",
      "Application : Calculer le nombre d'anagrammes d'un mot en tenant compte des repetitions.",
      "Maitriser : Utiliser les combinaisons : C(n ; k) = n!/(k!(n-k)!).",
      "Application : Verifier la relation C(n ; k) = C(n ; n-k).",
      "Connaitre le triangle de Pascal et la relation C(n ; k) = C(n-1 ; k-1) + C(n-1 ; k).",
      "Application : Developper (a + b) puissance n avec la formule du binome.",
      "Maitriser : Distinguer un tirage avec remise d'un tirage sans remise, simultane ou successif.",
      "Connaitre la probabilite conditionnelle : p(B sachant A) = p(A inter B)/p(A).",
      "Maitriser : Utiliser la formule des probabilites totales pour decomposer un evenement.",
      "Application : Construire et lire un arbre pondere (produits sur les branches, somme aux noeuds).",
      "Application : Verifier l'independance de deux evenements : p(A inter B) = p(A) x p(B).",
      "Connaitre la loi de probabilite d'une variable aleatoire discrete.",
      "Maitriser : Calculer l'esperance E(X) = somme des x(i) x p(i).",
      "Application : Calculer la variance et l'ecart type d'une variable aleatoire.",
      "Maitriser : Reconnaitre une loi binomiale de parametres n et p.",
      "Application : Calculer p(X = k) = C(n ; k) x p puissance k x (1 - p) puissance (n - k).",
      "Application : Calculer l'esperance d'une loi binomiale : E(X) = n p.",
      "Connaitre la loi uniforme discrete et son esperance.",
      "Connaitre les caracteristiques d'une serie statistique : moyenne, mediane, quartiles et ecart type.",
      "Maitriser : Calculer une moyenne ponderee, une mediane et des quartiles.",
      "Application : Interpreter la dispersion d'une serie avec l'ecart type.",
      "Application : Ajuster un nuage de points par une droite et interpreter la correlation.",
      "Application : Lire une courbe cumulative des frequences pour determiner mediane et quartiles.",
      "Application : Interpreter un resultat probabiliste dans le contexte de l'enonce.",
    ],
    methodes: [
      "1. Ecrire l'univers et verifier que les issues sont equiprobables avant de compter.",
      "2. Traduire l'evenement en langage ensembliste (union, intersection, contraire).",
      "3. Choisir l'outil de denombrement : factorielle, arrangement ou combinaison selon l'ordre et la repetition.",
      "4. Pour deux evenements : ecrire p(A union B) = p(A) + p(B) - p(A inter B).",
      "5. Pour une probabilite conditionnelle : identifier la condition et se placer dans la sous-population.",
      "6. Construire un arbre pondere quand l'experience se deroule en plusieurs etapes.",
      "7. Multiplier les probabilites le long d'une branche et additionner les branches donnant le meme resultat.",
      "8. Pour une variable aleatoire : lister les valeurs, puis calculer chaque probabilite.",
      "9. Calculer l'esperance en ponderant chaque valeur par sa probabilite.",
      "10. Pour une loi binomiale : verifier les conditions (epreuves identiques, independantes, deux issues).",
      "11. Pour une serie statistique : classer les donnees avant de calculer mediane et quartiles.",
      "12. Conclure par une phrase d'interpretation dans le contexte de l'enonce.",
    ],
    exemples: [
      "Exemple 1 : un de a 6 faces : p(nombre pair) = 3/6 = 1/2.",
      "Exemple 2 : deux des lances : p(somme egale a 7) = 6/36 = 1/6.",
      "Exemple 3 : si p(A) = 0,3 alors p(A barre) = 0,7.",
      "Exemple 4 : p(A) = 0,4, p(B) = 0,5 et p(A inter B) = 0,2 : p(A union B) = 0,7.",
      "Exemple 5 : 5! = 120 facons de ranger 5 livres differents.",
      "Exemple 6 : mots de 3 lettres distinctes parmi 5 : A(5 ; 3) = 60.",
      "Exemple 7 : C(10 ; 3) = 120 facons de choisir 3 eleves parmi 10.",
      "Exemple 8 : anagrammes de ANANAS : 6!/(3! x 2!) = 60.",
      "Exemple 9 : urne de 3 rouges et 2 noires : p(2 rouges) = C(3 ; 2)/C(5 ; 2) = 3/10.",
      "Exemple 10 : p(B sachant A) = 0,24/0,6 = 0,4.",
      "Exemple 11 : arbre de deux etapes : p(rouge puis rouge) = 0,6 x 0,5 = 0,30.",
      "Exemple 12 : X = nombre de faces en 2 lancers : p(0) = 1/4, p(1) = 1/2 et p(2) = 1/4.",
      "Exemple 13 : E(X) = 0 x 1/4 + 1 x 1/2 + 2 x 1/4 = 1.",
      "Exemple 14 : loi binomiale n = 10 et p = 0,3 : p(X = 2) = C(10 ; 2) x 0,09 x 0,7 puissance 8 = 0,2335.",
      "Exemple 15 : serie 4 ; 7 ; 7 ; 9 ; 13 : moyenne = 8, mediane = 7 et etendue = 9.",
    ],
    pieges: [
      "Supposer l'equiprobabilite sans la verifier (une piece ou un de pipe fausse le calcul).",
      "Confondre arrangement et combinaison : la question de l'ordre est la premiere a se poser.",
      "Oublier de soustraire p(A inter B) : les evenements comptes deux fois sont alors faux.",
      "Multiplier des probabilites sans verifier que les evenements sont independants.",
      "Appliquer la formule des probabilites totales en oubliant une branche de l'arbre.",
      "Confondre p(A sachant B) et p(B sachant A).",
      "Calculer une esperance en oubliant une valeur : la somme des probabilites doit valoir 1.",
      "Utiliser la loi binomiale sans verifier l'independance des epreuves.",
      "Confondre moyenne et mediane : une valeur extreme deplace la moyenne, pas la mediane.",
      "Calculer des quartiles sans avoir classe les donnees par ordre croissant.",
    ],
    cles: [
      "Equiprobabilite : p(A) = nombre de cas favorables / nombre de cas possibles.",
      "p(A barre) = 1 - p(A).",
      "p(A union B) = p(A) + p(B) - p(A inter B).",
      "Independance : p(A inter B) = p(A) x p(B).",
      "Factorielle : n! = n x (n-1) x ... x 1 et 0! = 1.",
      "Combinaisons : C(n ; k) = n!/(k!(n-k)!) et C(n ; k) = C(n ; n-k).",
      "Binome : (a + b) puissance n = somme des C(n ; k) a puissance k b puissance (n-k).",
      "p(B sachant A) = p(A inter B)/p(A) avec p(A) non nul.",
      "Esperance : E(X) = somme des x(i) p(i) ; loi binomiale : E(X) = n p.",
      "Statistiques : moyenne (valeur d'equilibre), mediane (valeur du milieu) et ecart type (dispersion).",
    ],
    autoEval: [
      "Calculer la probabilite d'obtenir un nombre premier avec un seul de a 6 faces.",
      "Deux des sont lances : quelle est la probabilite d'obtenir une somme superieure ou egale a 10 ?",
      "Combien de codes de 4 chiffres distincts peut-on former avec 1, 2, 3 et 4 ?",
      "Calculer C(12 ; 4).",
      "Dans une urne de 4 blanches et 6 noires, calculer la probabilite de tirer 2 blanches simultanement.",
      "p(A) = 0,5, p(B) = 0,4 et A, B independants : calculer p(A inter B) puis p(A union B).",
      "Construire l'arbre d'un tirage de deux boules sans remise et calculer p(deux boules de meme couleur).",
      "Une loi binomiale a n = 20 et p = 0,4 : calculer E(X) et p(X = 8).",
      "Calculer la mediane et les quartiles de la serie 3 ; 5 ; 7 ; 8 ; 11 ; 12 ; 15.",
      "Une serie a une moyenne de 10 et un ecart type de 2 : interpreter cette dispersion.",
    ],
  },
  physique: {
    objectifs: [
      "Connaitre les grandeurs, unites et symboles : longueur (m), masse (kg), temps (s), force (N) et energie (J).",
      "Application : Convertir une vitesse : 72 km/h = 20 m/s (division par 3,6).",
      "Maitriser : Distinguer un mouvement uniforme, accelere ou retarde a partir d'enregistrements.",
      "Application : Calculer une vitesse moyenne : v = d/t.",
      "Maitriser : Etudier un mouvement rectiligne uniformement varie (vitesse, acceleration, distance).",
      "Connaitre le mouvement circulaire uniforme et la notion de periode.",
      "Connaitre les trois lois de Newton et la notion de referentiel.",
      "Application : Appliquer la deuxieme loi de Newton : somme des forces = m x a.",
      "Maitriser : Realiser le bilan des forces d'un solide (poids, reaction, tension, frottement).",
      "Application : Etudier l'equilibre d'un solide soumis a deux ou trois forces coplanaires.",
      "Connaitre la relation poids-masse : P = m g avec g = 9,8 N/kg.",
      "Application : Calculer un poids et distinguer masse et poids.",
      "Maitriser : Calculer le travail d'une force constante : W = F d cos alpha.",
      "Application : Interpreter le signe du travail (moteur, resistant ou nul).",
      "Maitriser : Calculer l'energie cinetique (0,5 m v carre) et l'energie potentielle (m g h).",
      "Application : Appliquer la conservation de l'energie mecanique en l'absence de frottement.",
      "Maitriser : Utiliser le theoreme de l'energie cinetique : somme des travaux = variation de l'energie cinetique.",
      "Application : Calculer une puissance : P = W/t.",
      "Connaitre les lois de l'intensite et de la tension en serie et en derivation.",
      "Maitriser : Appliquer la loi d'Ohm : U = R I.",
      "Application : Calculer la puissance electrique (P = U I) et l'energie consommee (E = P t).",
      "Application : Determiner une resistance equivalente dans un montage simple.",
      "Connaitre la difference entre courant continu et alternatif (periode, frequence, valeur efficace).",
      "Connaitre le champ magnetique et l'effet d'un courant (experience d'Oersted).",
      "Application : Utiliser la force de Laplace : F = B I L sin alpha.",
      "Connaitre les caracteristiques d'une onde progressive : longueur d'onde, frequence et celerite.",
      "Application : Appliquer la relation v = lambda f et la periode T = 1/f.",
      "Connaitre la reflexion, la refraction et la reflexion totale (lois de Snell-Descartes).",
      "Maitriser : Construire l'image d'un objet par une lentille convergente (distance focale, grandissement).",
      "Application : Ecrire une equation de desintegration et utiliser la loi de decroissance radioactive (demi-vie).",
    ],
    methodes: [
      "1. Ecrire les donnees de l'enonce avec leurs unites avant tout calcul.",
      "2. Faire un schema (forces, montage ou rayon lumineux) : il evite la moitie des erreurs.",
      "3. Choisir le referentiel et le systeme etudies, puis definir le sens positif de l'axe.",
      "4. Pour la dynamique : faire le bilan des forces, puis projeter sur les axes.",
      "5. Pour la cinematique : identifier le type de mouvement avant d'utiliser les equations.",
      "6. Pour l'energie : ecrire le bilan entre l'etat initial et l'etat final (travaux et energies).",
      "7. Pour l'electricite : redessiner le circuit et reperer serie et derivation avant de calculer.",
      "8. Pour une onde : utiliser v = lambda f et convertir les unites (nm en m, kHz en Hz).",
      "9. Pour l'optique : tracer deux rayons particuliers pour localiser l'image.",
      "10. Pour une desintegration : equilibrer les nombres de masse et de charge.",
      "11. Verifier l'homogeneite et l'unite du resultat (m/s, N, J, W).",
      "12. Rediger avec la formule litterale, le calcul puis le resultat encadre.",
    ],
    exemples: [
      "Exemple 1 : v = d/t : 300 km en 4 h donnent v = 75 km/h.",
      "Exemple 2 : 72 km/h = 72/3,6 = 20 m/s.",
      "Exemple 3 : P = m g : 60 kg donnent P = 588 N avec g = 9,8 N/kg.",
      "Exemple 4 : W = F d cos alpha : F = 50 N, d = 4 m et alpha = 0 donnent W = 200 J.",
      "Exemple 5 : le travail du poids est nul lorsque le deplacement est horizontal (alpha = 90 degres).",
      "Exemple 6 : Ec = 0,5 x 2 x 9 = 9 J pour m = 2 kg et v = 3 m/s.",
      "Exemple 7 : Ep = m g h = 2 x 9,8 x 5 = 98 J.",
      "Exemple 8 : chute libre sans frottement : v = racine(2 g h) = racine(2 x 9,8 x 5) = 9,9 m/s.",
      "Exemple 9 : P = W/t : 600 J en 3 s donnent 200 W.",
      "Exemple 10 : U = R I : R = 40 ohms et I = 0,5 A donnent U = 20 V.",
      "Exemple 11 : P = U I = 220 x 0,5 = 110 W.",
      "Exemple 12 : resistances de 30 ohms et 20 ohms : Req = 50 ohms en serie et 12 ohms en derivation.",
      "Exemple 13 : onde de longueur d'onde 2 m et de frequence 50 Hz : v = 100 m/s.",
      "Exemple 14 : f = 1/T : T = 0,02 s donne f = 50 Hz.",
      "Exemple 15 : le carbone 14 qui emet un rayonnement beta moins se transforme en azote 14 (Z augmente de 1).",
    ],
    pieges: [
      "Melanger les unites : une vitesse en km/h et une distance en metres ne se combinent pas directement.",
      "Oublier de convertir les minutes en secondes (ou les km en m) avant le calcul.",
      "Confondre masse (kg) et poids (N) : le poids depend du lieu, pas la masse.",
      "Oublier le cos alpha dans le travail d'une force : alpha est l'angle entre la force et le deplacement.",
      "Confondre energie cinetique et energie potentielle dans le bilan energetique.",
      "Appliquer la conservation de l'energie mecanique en presence de frottements.",
      "Confondre serie (meme intensite) et derivation (meme tension) dans un circuit.",
      "Confondre puissance (W) et energie (J ou kWh) : la puissance est une energie par unite de temps.",
      "Utiliser la frequence a la place de la periode dans v = lambda f.",
      "Ecrire une desintegration sans verifier la conservation des nombres de masse et de charge.",
    ],
    cles: [
      "v = d/t ; v = lambda f ; T = 1/f.",
      "P = m g avec g = 9,8 N/kg : le poids s'exprime en newtons.",
      "Somme des forces = m x a (deuxieme loi de Newton).",
      "W = F d cos alpha : le travail se mesure en joules.",
      "Ec = 0,5 m v carre ; Ep = m g h ; Em = Ec + Ep.",
      "Theoreme de l'energie cinetique : somme des travaux = variation de l'energie cinetique.",
      "P = W/t ; en electricite P = U I et U = R I.",
      "Serie : I identique et U s'additionne ; derivation : U identique et I s'additionne.",
      "Onde progressive : v = lambda f ; la lumiere se propage beaucoup plus vite que le son.",
      "Radioactivite : la demi-vie est la duree au bout de laquelle la moitie des noyaux s'est desintegree.",
    ],
    autoEval: [
      "Convertir 108 km/h en m/s.",
      "Un solide de 5 kg est soumis a une force de 20 N sur 3 m dans le sens du mouvement : calculer le travail.",
      "Calculer l'energie cinetique d'une voiture de 1 200 kg roulant a 25 m/s.",
      "Un corps tombe de 20 m sans frottement : calculer sa vitesse a l'arrivee.",
      "Calculer la resistance equivalente de 12 ohms et 4 ohms montes en derivation.",
      "Un appareil de 500 W fonctionne 3 h : calculer l'energie consommee en kWh.",
      "Une onde de frequence 250 Hz se propage a 340 m/s : calculer sa longueur d'onde.",
      "Tracer l'image d'un objet place a deux fois la distance focale d'une lentille convergente.",
      "Le carbone 14 a une demi-vie de 5 730 ans : quelle fraction reste apres 11 460 ans ?",
      "Un rayon lumineux passe de l'air dans l'eau : dans quel sens est-il devie ? Justifier avec les indices.",
    ],
  },
  chimie: {
    objectifs: [
      "Connaitre la structure de l'atome : noyau (protons et neutrons) et electrons.",
      "Application : Determiner le nombre de protons, de neutrons et d'electrons d'un atome ou d'un ion.",
      "Maitriser : Ecrire la configuration electronique et en deduire la position dans le tableau periodique.",
      "Application : Relier la position dans le tableau periodique aux proprietes (famille, valence).",
      "Connaitre les ions monoatomiques usuels et la regle d'electroneutralite.",
      "Maitriser : Ecrire la formule statistique d'un compose et calculer sa masse molaire.",
      "Connaitre la mole et la constante d'Avogadro : N = n x N(A).",
      "Application : Calculer une quantite de matiere : n = m/M.",
      "Application : Calculer une concentration molaire : C = n/V.",
      "Maitriser : Preparer une solution par dissolution ou par dilution (facteur de dilution).",
      "Application : Utiliser la conservation de la matiere lors d'une dilution : C1 V1 = C2 V2.",
      "Connaitre la dissolution d'un solide ionique et l'equation de dissolution du chlorure de sodium.",
      "Connaitre la difference entre acide et base (Brønsted) et la notion de couple acide/base.",
      "Application : Ecrire une reaction acido-basique et identifier les couples engages.",
      "Maitriser : Calculer le pH d'une solution d'acide fort (pH = -log C) et la concentration a partir du pH.",
      "Application : Determiner si une solution est acide, basique ou neutre et utiliser le produit ionique de l'eau.",
      "Maitriser : Realiser et exploiter un dosage acido-basique (equivalence).",
      "Application : Utiliser la relation a l'equivalence C(A) V(A) = C(B) V(B) pour un monoacide et une monobase.",
      "Connaitre l'oxydation, la reduction et la notion de couple oxydant/reducteur.",
      "Application : Ecrire et equilibrer une demi-equation electronique puis une reaction d'oxydoreduction.",
      "Maitriser : Identifier l'oxydant, le reducteur, l'espece oxydee et l'espece reduite dans une pile.",
      "Connaitre le fonctionnement d'une pile electrochimique : anode, cathode et pont salin.",
      "Application : Ecrire les reactions aux electrodes et determiner la polarite d'une pile.",
      "Maitriser : Utiliser la classification electrochimique des couples pour prevoir une reaction.",
      "Connaitre les hydrocarbures : alcanes, alcenes, alcynes et leurs formules generales.",
      "Application : Ecrire la formule semi-developpee d'un compose organique et le nommer.",
      "Maitriser : Distinguer une reaction de substitution, d'addition et d'elimination.",
      "Connaitre les groupes caracteristiques : alcool, acide carboxylique, ester, aldehyde et cetone.",
      "Application : Ecrire une reaction d'esterification et reconnaitre un ester.",
      "Maitriser : Utiliser la nomenclature officielle pour nommer un compose a chaine courte.",
    ],
    methodes: [
      "1. Ecrire les donnees avec leurs unites et l'equation-bilan avant tout calcul.",
      "2. Verifier l'equilibre de l'equation : autant d'atomes de chaque element de part et d'autre.",
      "3. Pour un calcul de quantite : passer par la mole (n = m/M ou n = C x V).",
      "4. Pour une dissolution : ecrire l'equation de dissolution pour connaitre les ions formes.",
      "5. Pour une dilution : utiliser C1 V1 = C2 V2 et verifier que C2 < C1.",
      "6. Pour le pH : utiliser pH = -log C pour un acide fort et une puissance de 10 pour la concentration.",
      "7. Pour un dosage : ecrire l'equation-bilan puis la relation a l'equivalence en tenant compte des coefficients.",
      "8. Pour une oxydoreduction : equilibrer d'abord les demi-equations, puis les combiner.",
      "9. Pour une pile : situer l'anode (oxydation) et la cathode (reduction) puis en deduire la polarite.",
      "10. Pour la chimie organique : identifier la chaine principale et les groupes caracteristiques avant de nommer.",
      "11. Pour une transformation : verifier la conservation de la matiere et de la charge.",
      "12. Rediger la conclusion avec l'unite (mol, mol/L, g) et un nombre coherent de chiffres significatifs.",
    ],
    exemples: [
      "Exemple 1 : l'atome de sodium (Z = 11, A = 23) a 11 protons, 12 neutrons et 11 electrons.",
      "Exemple 2 : l'ion chlorure Cl moins (Z = 17) a 18 electrons.",
      "Exemple 3 : configuration du sodium : 1s carre 2s carre 2p puissance 6 3s puissance 1 : 3e periode, 1re colonne.",
      "Exemple 4 : masse molaire de l'eau H2O : 2 x 1 + 16 = 18 g/mol.",
      "Exemple 5 : n = m/M : 36 g d'eau donnent n = 2 mol, soit 1,2 x 10 puissance 24 molecules.",
      "Exemple 6 : C = n/V : 0,5 mol dans 2 L donne C = 0,25 mol/L.",
      "Exemple 7 : NaCl solide donne Na plus et Cl moins : 1 mol de NaCl donne 1 mol de chaque ion.",
      "Exemple 8 : dilution : 10 mL a 5 mol/L portes a 100 mL donnent C2 = 0,5 mol/L.",
      "Exemple 9 : acide fort a 10 puissance -3 mol/L : pH = 3.",
      "Exemple 10 : pH = 11,4 donne pOH = 2,6 et une concentration en hydroxyde de 2,5 x 10 puissance -3 mol/L.",
      "Exemple 11 : dosage d'un acide par une base forte : a l'equivalence, C(A) V(A) = C(B) V(B).",
      "Exemple 12 : demi-equations : Zn donne Zn 2 plus + 2 e moins ; Cu 2 plus + 2 e moins donne Cu.",
      "Exemple 13 : pile Zn/Cu : l'anode est le zinc (oxydation) et la cathode le cuivre (reduction).",
      "Exemple 14 : esterification : acide ethanoique + ethanol donne ethanoate d'ethyle + eau.",
      "Exemple 15 : combustion complete du propane : C3H8 + 5 O2 donne 3 CO2 + 4 H2O.",
    ],
    pieges: [
      "Utiliser une equation-bilan non equilibree pour le calcul des quantites.",
      "Confondre masse molaire et masse : M s'exprime en g/mol et m en g.",
      "Confondre mole et molecule : une mole contient 6,02 x 10 puissance 23 molecules.",
      "Utiliser C1 V1 = C2 V2 avec des volumes dans des unites differentes.",
      "Confondre acide fort et acide faible dans le calcul du pH.",
      "Oublier que pH + pOH = 14 a 25 degres.",
      "Oublier les coefficients de l'equation dans la relation a l'equivalence.",
      "Ecrire une demi-equation electronique sans equilibrer les charges.",
      "Inverser anode et cathode : l'anode est le siege de l'oxydation.",
      "Confondre le groupe acide carboxylique et le groupe ester dans la nomenclature.",
    ],
    cles: [
      "Atome : Z protons, A nucleons et A - Z neutrons ; l'atome est electriquement neutre.",
      "n = m/M = N/N(A) = C x V.",
      "Masse molaire : somme des masses atomiques (H2O = 18 g/mol).",
      "pH = -log C pour un acide fort ; pH + pOH = 14 a 25 degres.",
      "Dilution : C1 V1 = C2 V2 ; a l'equivalence : coefficients x concentrations x volumes egaux.",
      "Oxydation = perte d'electrons ; reduction = gain d'electrons.",
      "Pile : anode = oxydation (pole moins) et cathode = reduction (pole plus).",
      "Alcane C(n)H(2n+2) ; alcene C(n)H(2n) : la double liaison fait la difference.",
      "Groupes caracteristiques : OH (alcool), COOH (acide carboxylique), COO (ester).",
      "Une transformation chimique conserve les elements et la charge electrique.",
    ],
    autoEval: [
      "Donner la structure de l'atome de chlore (Z = 17, A = 35) et de son ion chlorure.",
      "Calculer la masse molaire du sulfate de cuivre CuSO4 (Cu = 63,5 ; S = 32 ; O = 16).",
      "Calculer la quantite de matiere contenue dans 4 g de soude NaOH (M = 40 g/mol).",
      "On dilue 20 mL d'une solution a 2 mol/L dans 200 mL : calculer la concentration finale.",
      "Calculer le pH d'une solution d'acide chlorhydrique a 0,01 mol/L.",
      "Une solution a pH = 3,5 : est-elle acide ou basique ? Que vaut sa concentration en protons ?",
      "Ecrire l'equation-bilan entre l'acide chlorhydrique et la soude, puis indiquer les couples.",
      "Ecrire les demi-equations de la pile Zn/Cu puis l'equation-bilan.",
      "Donner la formule semi-developpee et le nom de l'alcane a 5 atomes de carbone.",
      "Ecrire l'equation de la combustion complete du methane dans le dioxygene.",
    ],
  },
  complexes: {
    objectifs: [
      "Connaitre la forme algebrique d'un nombre complexe : z = a + ib avec a = Re(z), b = Im(z) et i carre = -1.",
      "Application : Identifier partie reelle et partie imaginaire (ex : z = 3 - 5i donne Re(z) = 3 et Im(z) = -5).",
      "Maitriser : Calculer le conjugue d'un complexe : si z = a + ib alors z barre = a - ib.",
      "Application : Utiliser z x z barre = a carre + b carre, qui est toujours un reel positif ou nul.",
      "Maitriser : Calculer le module |z| = racine(a carre + b carre) et l'interpreter comme la distance OM.",
      "Maitriser : Effectuer somme, difference et produit en regroupant parties reelles et parties imaginaires.",
      "Maitriser : Calculer le quotient de deux complexes en multipliant par le conjugue du denominateur.",
      "Connaitre les puissances de i : i carre = -1, i cube = -i, i puissance 4 = 1 (cycle de periode 4).",
      "Resoudre az carre + bz + c = 0 avec discriminant negatif : z = (-b +/- i racine(-D)) / (2a).",
      "Placer un complexe dans le plan : z = a + ib est l'affixe du point M(a ; b).",
      "Maitriser : Calculer l'argument et passer a la forme trigonometrique z = r(cos theta + i sin theta).",
      "Maitriser : Utiliser la forme exponentielle z = r e puissance (i theta) pour produits, quotients et puissances.",
      "Application : Appliquer la formule de Moivre : (cos theta + i sin theta) puissance n = cos(n theta) + i sin(n theta).",
      "Application : Appliquer les formules d'Euler pour lineariser cos carre(x) = (1 + cos(2x))/2 et calculer une primitive.",
      "Application : Determiner les racines n-iemes d'un complexe et les interpreter geometriquement.",
      "Application : Traduire une translation, une rotation ou une homothetie par une ecriture complexe.",
    ],
    methodes: [
      "1. Identifier Re(z) et Im(z) avant tout calcul : c'est le reflexe de depart obligatoire.",
      "2. Pour le conjugue : changer le signe de la partie imaginaire uniquement, rien d'autre.",
      "3. Pour le module : calculer a carre + b carre puis prendre la racine carree ; ne jamais oublier la racine.",
      "4. Pour une somme ou une difference : regrouper les reels ensemble et les imaginaires ensemble.",
      "5. Pour un produit : developper puis remplacer i carre par -1 avant de simplifier.",
      "6. Pour un quotient : multiplier numerateur et denominateur par le conjugue du denominateur.",
      "7. Pour i puissance n : diviser n par 4 et utiliser le reste (0, 1, 2 ou 3).",
      "8. Pour une equation du second degre : calculer D ; si D est negatif, les deux racines sont conjuguees.",
      "9. Pour l'argument : calculer cos theta = a/r et sin theta = b/r, puis placer le point pour fixer le signe.",
      "10. Pour un produit en forme exponentielle : multiplier les modules et additionner les arguments.",
      "11. Pour une puissance : utiliser Moivre ou la forme exponentielle (r puissance n, n theta).",
      "12. Verifier chaque resultat en reinjectant la solution : z x z barre doit etre un reel positif.",
    ],
    exemples: [
      "Exemple 1 : z = 2 + 3i. Re(z) = 2, Im(z) = 3, z barre = 2 - 3i et |z| = racine(4 + 9) = racine(13) = 3,61.",
      "Exemple 2 : (1 + 2i)(3 - i) = 3 - i + 6i - 2i carre = 3 + 5i + 2 = 5 + 5i.",
      "Exemple 3 : 1/(1 + i) = (1 - i)/((1 + i)(1 - i)) = (1 - i)/2 = 0,5 - 0,5i.",
      "Exemple 4 : i puissance 37 : 37 = 4 x 9 + 1, donc i puissance 37 = i puissance 1 = i.",
      "Exemple 5 : z carre + z + 1 = 0. D = 1 - 4 = -3 < 0, donc z = (-1 + i racine(3))/2 ou z = (-1 - i racine(3))/2.",
      "Exemple 6 : z = 1 + i racine(3). |z| = racine(1 + 3) = 2 ; cos theta = 1/2 et sin theta = racine(3)/2 donc theta = pi/3 et z = 2 e puissance (i pi/3).",
      "Exemple 7 : (1 + i) puissance 8. Or 1 + i = racine(2) e puissance (i pi/4), donc (1 + i) puissance 8 = (racine(2)) puissance 8 x e puissance (i 2pi) = 16.",
      "Exemple 8 : z1 = 2 + i et z2 = -1 + 2i. Alors |z1 - z2| = |3 - i| = racine(10) = distance M1M2.",
      "Exemple 9 : z carre = -4 donne z = 2i ou z = -2i : les deux racines sont des imaginaires purs conjugues.",
      "Exemple 10 : avec Euler, cos carre(t) = ((e puissance(it) + e puissance(-it))/2) carre = (1 + cos(2t))/2.",
      "Exemple 11 : Moivre : (cos(pi/6) + i sin(pi/6)) puissance 3 = cos(pi/2) + i sin(pi/2) = i.",
      "Exemple 12 : z puissance 3 = 1 donne z = 1, z = e puissance(2i pi/3) et z = e puissance(4i pi/3) : trois points formant un triangle equilateral.",
      "Exemple 13 : rotation de centre O et d'angle pi/2 : z' = i z. Le point M(2 ; 0) a pour image M'(0 ; 2).",
      "Exemple 14 : z carre - 3z + 3 = 0. D = 9 - 12 = -3, racines (3 +/- i racine(3))/2 et leur somme vaut 3 = -b/a.",
      "Exemple 15 : |z - (1 + i)| = 2 est l'ensemble des points M d'affixe z a la distance 2 de A(1 ; 1) : cercle de centre A et de rayon 2.",
    ],
    pieges: [
      "Confondre i carre = -1 avec i carre = 1 : c'est la source de presque toutes les erreurs de calcul.",
      "Oublier de remplacer i carre par -1 dans un produit developpe.",
      "Ecrire |z| = a carre + b carre : le module est la racine carree, pas le carre.",
      "Croire que z x z barre peut etre negatif : c'est toujours un reel positif ou nul, egal a |z| carre.",
      "Utiliser racine(D) au lieu de racine(-D) dans la formule des racines quand le discriminant est negatif.",
      "Oublier l'identification des parties reelles et imaginaires pour resoudre z1 = z2.",
      "Ecrire z barre = -z : c'est faux en general, cela n'est vrai que pour un imaginaire pur.",
      "Confondre module et argument dans la forme exponentielle : r = |z| et theta = arg(z).",
      "Oublier que l'argument est defini modulo 2pi : toutes les solutions z_k s'obtiennent en ajoutant 2k pi.",
      "Dans une division, multiplier par le conjugue du denominateur et non celui du numerateur.",
    ],
    cles: [
      "i carre = -1 ; les puissances de i suivent le cycle i, -1, -i, 1 de periode 4.",
      "z = a + ib : Re(z) = a, Im(z) = b et z barre = a - ib.",
      "|z| = racine(a carre + b carre) et z x z barre = |z| carre.",
      "Deux complexes sont egaux si et seulement si ils ont meme partie reelle et meme partie imaginaire.",
      "Forme trigonometrique : z = r(cos theta + i sin theta) avec r = |z| superieur a 0.",
      "Forme exponentielle : z = r e puissance (i theta) : la plus commode pour les produits et les puissances.",
      "Produit : on multiplie les modules et on additionne les arguments ; quotient : on divise et on soustrait.",
      "Moivre : (cos theta + i sin theta) puissance n = cos(n theta) + i sin(n theta).",
      "Euler : cos theta = (e puissance(i theta) + e puissance(-i theta))/2 et sin theta = (e puissance(i theta) - e puissance(-i theta))/(2i).",
      "Si D est negatif, az carre + bz + c = 0 admet deux racines complexes conjuguees.",
      "|zB - zA| = AB : le module d'une difference de complexes mesure une distance.",
      "Racines n-iemes : z_k = racine n-ieme de r x e puissance(i(theta + 2k pi)/n), k de 0 a n-1.",
    ],
    autoEval: [
      "Calculer Re(z), Im(z), z barre et |z| pour z = 4 - 3i.",
      "Calculer (2 + i)(1 - 3i) et donner le resultat sous forme algebrique.",
      "Ecrire (3 + i)/(1 - 2i) sous la forme a + ib.",
      "Calculer i puissance 2019 en justifiant avec le reste de la division par 4.",
      "Resoudre dans l'ensemble des complexes z carre - 4z + 13 = 0.",
      "Ecrire z = -1 + i racine(3) sous forme trigonometrique puis sous forme exponentielle.",
      "Calculer (1 - i) puissance 6 a l'aide de la forme exponentielle.",
      "Demontrer que cos carre(x) = (1 + cos(2x))/2 en utilisant les formules d'Euler.",
      "Determiner les racines quatriemes de l'unite et les placer dans le plan complexe.",
      "Determiner et representer l'ensemble des points M d'affixe z tels que |z - 2i| = 3.",
    ],
  },
  svt: {
    objectifs: [
      "Connaitre l'organisation de la cellule : membrane, cytoplasme, noyau et organites.",
      "Application : Distinguer une cellule animale d'une cellule vegetale (paroi, chloroplastes, vacuole).",
      "Maitriser : Relier chaque organite a sa fonction (mitochondrie : energie ; chloroplaste : photosynthese).",
      "Connaitre les echanges de matiere entre la cellule et son milieu (diffusion, osmose).",
      "Maitriser : Ecrire l'equation-bilan de la photosynthese : 6 CO2 + 6 H2O donne C6H12O6 + 6 O2 (a la lumiere).",
      "Application : Identifier le siege de la photosynthese (chlorophylle) et ses facteurs (lumiere, CO2, temperature).",
      "Maitriser : Ecrire l'equation-bilan de la respiration cellulaire et la distinguer de la fermentation.",
      "Application : Comparer les rendements energetiques de la respiration et de la fermentation.",
      "Connaitre le role des stomates et les echanges gazeux de la feuille.",
      "Application : Interpreter une experience de mesure de O2 et de CO2 (ExAO).",
      "Connaitre le support de l'information genetique : l'ADN, sa structure et sa replication.",
      "Application : Relier gene, chromosome et caractere hereditaire.",
      "Maitriser : Decrire la mitose et expliquer la conservation du nombre de chromosomes.",
      "Application : Decrire la meiose et expliquer le brassage genetique (inter et intrachromosomique).",
      "Maitriser : Utiliser un echiquier de croisement pour prevoir les proportions phenotypiques.",
      "Application : Interpreter un arbre genealogique et determiner le mode de transmission d'un caractere.",
      "Connaitre les anomalies chromosomiques (trisomie 21) et les groupes sanguins.",
      "Connaitre les defenses de l'organisme : immunite innee et immunite adaptative.",
      "Application : Distinguer la reponse humorale (anticorps) de la reponse cellulaire (lymphocytes T).",
      "Maitriser : Expliquer le principe de la vaccination et de la serotherapie.",
      "Application : Expliquer le mode d'action du VIH et ses consequences sur le systeme immunitaire.",
      "Connaitre le tissu nerveux : neurone, synapse et message nerveux.",
      "Application : Decrire un arc reflexe et le trajet du message nerveux.",
      "Connaitre les ecosystemes : biotope, biocenose et chaines alimentaires.",
      "Application : Construire une chaine alimentaire et analyser le flux de matiere et d'energie.",
      "Application : Expliquer les causes et les consequences de la degradation des sols (erosion au Niger).",
      "Maitriser : Proposer des mesures de gestion durable (reboisement, cordons pierreux, agroforesterie).",
      "Connaitre la structure interne de la Terre et expliquer l'origine des seismes.",
      "Application : Expliquer la tectonique des plaques et la formation des reliefs.",
      "Maitriser : Relier les ressources du sous-sol nigerien (uranium d'Arlit, charbon d'Anou-Araren) a leur formation.",
    ],
    methodes: [
      "1. Lire l'enonce et identifier le phenomene etudie (nutrition, information genetique, immunite, ecologie).",
      "2. Faire un schema clair et titre : legende, titre et echelle sont exiges a l'examen.",
      "3. Pour une experience : identifier le temoin et le seul facteur teste a la fois.",
      "4. Formuler une hypothese puis la confronter aux resultats observes.",
      "5. Pour un croisement : ecrire les genotypes des parents, les gametes, puis l'echiquier.",
      "6. Pour un arbre genealogique : reperer les personnes atteintes et remonter au mode de transmission.",
      "7. Pour l'immunite : distinguer la reponse immediate (innee) de la reponse specifique (adaptative).",
      "8. Pour une chaine alimentaire : respecter le sens des fleches (de l'aliment vers le consommateur).",
      "9. Pour un cycle : ordonner les etapes et preciser le role de chaque element (plante, animal, sol).",
      "10. Pour une reaction du corps (effort, infection, vaccin) : relier cause, mecanisme et consequence.",
      "11. Utiliser le vocabulaire exact : biotope, biocenose, anticorps, synapse, allele.",
      "12. Conclure en repondant directement a la question avec les observations comme preuve.",
    ],
    exemples: [
      "Exemple 1 : cellules vegetales au microscope : paroi, vacuole et chloroplastes visibles.",
      "Exemple 2 : photosynthese : une feuille eclairee consomme du CO2 et libere du O2 en volumes egaux.",
      "Exemple 3 : fermentation : une levure en anaerobiose transforme le glucose en ethanol et en CO2.",
      "Exemple 4 : une cellule vegetale placee dans un milieu tres sale perd son eau et se plasmolise.",
      "Exemple 5 : ADN : les bases A-T et C-G sont complementaires, une chaine indique donc l'autre.",
      "Exemple 6 : mitose : une cellule a 8 chromosomes donne deux cellules a 8 chromosomes.",
      "Exemple 7 : meiose : une cellule a 2n = 8 chromosomes donne des gametes a 4 chromosomes.",
      "Exemple 8 : croisement Aa x Aa : 3/4 des descendants expriment le caractere dominant et 1/4 le recessif.",
      "Exemple 9 : groupe sanguin : deux parents AO et BO peuvent avoir un enfant O.",
      "Exemple 10 : immunite : apres la vaccination, les anticorps specifiques apparaissent plus vite.",
      "Exemple 11 : arc reflexe : recepteur, nerf sensitif, moelle epiniere, nerf moteur, muscle.",
      "Exemple 12 : chaine alimentaire : herbe, criquet, lezard, aigle (fleches dans le sens de la matiere).",
      "Exemple 13 : un sol nu se degrasse beaucoup plus vite qu'un sol couvert de vegetation.",
      "Exemple 14 : seisme : les ondes sismiques partent du foyer et atteignent les stations d'enregistrement.",
      "Exemple 15 : uranium d'Arlit : formation en milieu sedimentaire puis concentration dans des gres.",
    ],
    pieges: [
      "Confondre photosynthese (stockage d'energie) et respiration (liberation d'energie).",
      "Ecrire les equations-bilans sans les equilibrer (6 CO2 et 6 H2O).",
      "Oublier de mentionner la lumiere comme condition de la photosynthese.",
      "Confondre mitose (deux cellules diploides identiques) et meiose (quatre cellules haploides differentes).",
      "Oublier de preciser les genotypes des gametes dans un croisement.",
      "Inverser le sens des fleches dans une chaine alimentaire.",
      "Confondre anticorps (produit par l'organisme) et antigenes (portes par l'agent infectieux).",
      "Confondre immunite innee (immediate et non specifique) et immunite adaptative (specifique et avec memoire).",
      "Confondre biotope (le milieu) et biocenose (les etres vivants).",
      "Faire un schema sans legende, sans titre ou sans respecter les proportions.",
    ],
    cles: [
      "Cellule : membrane, cytoplasme, noyau ; mitochondries = respiration et chloroplastes = photosynthese.",
      "Photosynthese : 6 CO2 + 6 H2O + lumiere donne C6H12O6 + 6 O2.",
      "Respiration : C6H12O6 + 6 O2 donne 6 CO2 + 6 H2O + energie.",
      "ADN : deux chaines complementaires (A-T et C-G) ; un gene est un segment d'ADN.",
      "Mitose : conservation du nombre de chromosomes ; meiose : reduction de moitie et brassage.",
      "Heredite : echiquier de croisement, proportions phenotypiques et groupes sanguins A, B, AB et O.",
      "Immunite adaptative : anticorps (humorale) et lymphocytes T (cellulaire) ; vaccination = memoire.",
      "Arc reflexe : recepteur, neurone sensitif, centre nerveux, neurone moteur et effecteur.",
      "Ecosysteme : biotope + biocenose ; la matiere circule et l'energie se degrade le long des chaines.",
      "Sols et ressources : la vegetation protege le sol ; uranium et charbon sont non renouvelables.",
    ],
    autoEval: [
      "Ecrire l'equation-bilan de la photosynthese et preciser ses facteurs limitants.",
      "Comparer l'energie produite par la respiration aerobie et par la fermentation pour une mole de glucose.",
      "Un homme de genotype AO et une femme de genotype BO : quels groupes sanguins peuvent avoir leurs enfants ?",
      "Expliquer pourquoi la mitose conserve le nombre de chromosomes.",
      "Une mere est atteinte d'une maladie genetique liee a l'X et le pere est sain : quels enfants peuvent etre atteints ?",
      "Decrire les etapes de la reponse immunitaire apres une vaccination.",
      "Expliquer le trajet du message nerveux lors du reflexe myotatique.",
      "Construire une chaine alimentaire de 4 maillons dans un ecosysteme sahelien.",
      "Expliquer deux causes de la degradation des sols au Niger et proposer une solution.",
      "Decrire la structure interne de la Terre et expliquer l'origine des seismes.",
    ],
  },
  general: {
    objectifs: [
      "Connaitre le format de l'epreuve : duree, nombre d'exercices et bareme indicatif.",
      "Application : Repartir le temps : environ 1 minute par point puis 15 minutes de relecture.",
      "Maitriser : Lire tout le sujet avant de commencer et identifier les exercices les plus accessibles.",
      "Application : Commencer par l'exercice le mieux maitrise pour securiser des points.",
      "Maitriser : Rediger une reponse structuree : formule, calcul, resultat encadre et phrase de conclusion.",
      "Application : Justifier chaque reponse par une propriete, une loi ou une donnee du document.",
      "Connaitre les unites du systeme international et les conversions les plus utiles.",
      "Application : Verifier la coherence d'un resultat par un ordre de grandeur.",
      "Maitriser : Encadrer un resultat numerique et respecter les chiffres significatifs.",
      "Application : Convertir des unites composees (km/h en m/s, g/cm cube en kg/m cube).",
      "Connaitre les symboles mathematiques usuels (union, intersection, racine carree, valeur absolue).",
      "Application : Traduire un enonce en equations (mise en equation d'un probleme).",
      "Maitriser : Utiliser une calculatrice efficacement (modes, parentheses, memoire).",
      "Application : Calculer de tete : doubles, moities, pourcentages et carres simples.",
      "Maitriser : Exploiter un graphique : axes, unites, echelle et points remarquables.",
      "Application : Interpreter un coefficient directeur comme un taux de variation.",
      "Maitriser : Exploiter un tableau de donnees (moyenne, comparaison, tendance).",
      "Connaitre les etapes d'une demarche scientifique : observation, hypothese, experience, conclusion.",
      "Application : Identifier le temoin et la variable dans un protocole experimental.",
      "Maitriser : Presenter un schema : titre, legende, echelle et proprete.",
      "Application : Analyser un document (texte, schema, tableau, graphique) en relevant les informations cles.",
      "Maitriser : Argumenter une reponse avec les donnees du document et les connaissances du cours.",
      "Connaitre les methodes de revision efficaces : espacement, auto-evaluation et resume actif.",
      "Application : Planifier une semaine de revision en alternant les matieres.",
      "Application : Transformer chaque erreur en exercice de re-entrainement.",
      "Maitriser : Gerer le stress : sommeil, respiration, hydratation et gestion du temps.",
      "Application : S'auto-evaluer avec un sujet complet en conditions reelles.",
      "Application : Relire une copie pour traquer les erreurs d'unites, de signe et de calcul.",
      "Connaitre les pieges classiques du BAC par matiere : unites, hypotheses oubliees, theoremes mal cites.",
      "Application : Tenir un carnet d'erreurs par matiere et le relire avant l'epreuve.",
    ],
    methodes: [
      "1. Lire l'enonce deux fois et souligner les donnees et la question posee.",
      "2. Ecrire ce que l'on cherche et l'unite attendue avant de calculer.",
      "3. Choisir la formule ou la loi du cours qui relie les donnees a l'inconnue.",
      "4. Ecrire la formule litterale, puis remplacer par les valeurs.",
      "5. Faire le calcul en gardant les unites et verifier l'ordre de grandeur.",
      "6. Encadrer le resultat et preciser son unite.",
      "7. Rediger une phrase de conclusion qui repond directement a la question.",
      "8. Si un exercice bloque : passer au suivant et y revenir (le temps est une ressource).",
      "9. Relire les questions a la fin pour verifier qu'aucune n'a ete oubliee.",
      "10. Verifier les signes, les parentheses et les conversions dans chaque calcul.",
      "11. S'auto-evaluer regulierement en conditions d'examen pour habituer le rythme.",
      "12. Relire son carnet d'erreurs la veille pour eviter les fautes deja faites.",
    ],
    exemples: [
      "Exemple 1 : une epreuve de 20 points duree 3 h : environ 9 minutes par point avant relecture.",
      "Exemple 2 : un enonce donne v = 72 km/h : la reponse en m/s vaut 20 m/s.",
      "Exemple 3 : une vitesse de marche trouvee a 0,5 m/s est un ordre de grandeur plausible.",
      "Exemple 4 : une hausse de 10 pour cent sur 250 crédits donne 275.",
      "Exemple 5 : une droite qui monte de 6 quand l'abscisse augmente de 2 a pour coefficient 3.",
      "Exemple 6 : sur un schema de forces, 1 cm peut representer 10 N (echelle a preciser).",
      "Exemple 7 : 2,5 m cube = 2 500 dm cube = 2 500 L.",
      "Exemple 8 : 4,78 s s'arrondit a 4,8 s si la donnee ne porte que 2 chiffres significatifs.",
      "Exemple 9 : moyenne d'une classe = somme des notes / nombre d'eleves.",
      "Exemple 10 : une hausse de 15 pour cent puis une baisse de 15 pour cent ne redonne pas le prix initial.",
      "Exemple 11 : un schema reussi porte un titre, une legende et une echelle.",
      "Exemple 12 : reponse structuree : formule, substitution, resultat, conclusion.",
      "Exemple 13 : trois seances de 25 minutes espacees valent mieux qu'une seule seance de 2 h.",
      "Exemple 14 : une distance lue en cm et utilisee comme des metres fausse tout le resultat.",
      "Exemple 15 : a la relecture, verifier chaque resultat encadre contre l'unite demandee par l'enonce.",
    ],
    pieges: [
      "Repondre sans lire la question jusqu'au bout : une unite ou une justification est souvent demandee.",
      "Oublier l'unite dans le resultat final.",
      "Utiliser une formule sans verifier ses conditions d'application.",
      "Arrondir trop tot : garder les valeurs exactes jusqu'au dernier calcul.",
      "Confondre les donnees de l'enonce avec celles d'un autre exercice.",
      "Negliger la redaction : une reponse juste mais non justifiee perd des points.",
      "Passer trop de temps sur un exercice difficile et manquer de temps pour les autres.",
      "Oublier la phrase de conclusion qui repond a la question posee.",
      "Ne pas verifier l'ordre de grandeur d'un resultat numerique.",
      "Reviser en relisant passivement au lieu de s'auto-evaluer.",
    ],
    cles: [
      "Repartir le temps selon les points et garder 10 a 15 minutes de relecture.",
      "Formule litterale, puis valeurs, puis resultat encadre avec son unite.",
      "Toujours justifier avec une propriete, une loi ou une donnee du document.",
      "Verifier l'ordre de grandeur et les unites pour detecter les erreurs de calcul.",
      "Un schema complet porte un titre, une legende et une echelle.",
      "Un graphique se lit avec ses axes, ses unites et son echelle avant toute interpretation.",
      "Une revision active (s'auto-evaluer) est plus efficace qu'une relecture passive.",
      "Espacer les revisions dans le temps ancre durablement les connaissances.",
      "Le carnet d'erreurs transforme chaque faute en progres mesurable.",
      "Le jour de l'epreuve : sommeil, hydratation, lecture complete du sujet et gestion du temps.",
    ],
    autoEval: [
      "Repartir 4 h d'epreuve sur un sujet de 20 points et indiquer le temps par exercice.",
      "Convertir 45 km/h en m/s puis verifier l'ordre de grandeur.",
      "Un poids d'eleve calcule a 0,002 N est-il plausible ? Corriger le calcul.",
      "Traduire en equation : le triple d'un nombre auquel on ajoute 7 vaut 31.",
      "Citer trois elements obligatoires d'un schema scientifique.",
      "Expliquer pourquoi une hausse de 20 pour cent suivie d'une baisse de 20 pour cent ne redonne pas le prix initial.",
      "Proposer un planning de revision d'une semaine pour trois matieres.",
      "Un eleve trouve une duree de 20 s pour un trajet de 400 m effectue en 20 s : expliquer son erreur.",
      "Donner deux methodes pour verifier un calcul sans le refaire.",
      "Decrire une situation ou l'ordre de grandeur permet de detecter une erreur de conversion.",
    ],
  },
};

export function genererSectionsCours(titre: string, matiere?: string, contenu?: string): SectionCours[] {
  const theme = detecterTheme(titre, matiere);
  const g = GABARITS[theme];
  const sujet = majuscule((titre || "ce chapitre").trim());

  const sections: SectionCours[] = [];

  sections.push({ emoji: "🎯", titre: "Objectifs du chapitre", lignes: g.objectifs });

  sections.push({
    emoji: "🛠️",
    titre: "Méthode pas-à-pas",
    lignes: [`Pour réussir « ${sujet} », suis cette démarche :`, ...g.methodes],
  });

  sections.push({
    emoji: "💡",
    titre: "Exemples d'application",
    lignes: [`Exemples types autour de « ${sujet} » :`, ...g.exemples],
  });

  sections.push({ emoji: "🚫", titre: "Erreurs fréquentes à éviter", lignes: g.pieges });
  sections.push({ emoji: "📌", titre: "Points clés à retenir", lignes: g.cles });
  sections.push({ emoji: "✅", titre: "Questions d'auto-évaluation", lignes: g.autoEval });

  // 📐 Schéma annoté si le chapitre s'y prête
  const schema = schemaPourChapitre(titre);
  if (schema) {
    sections.push({ emoji: "📐", titre: `Schéma : ${schema.titre}`, lignes: [schema.art, "", `➡️ ${schema.legende}`] });
  }

  return sections;
}

/** Concatène toutes les sections en un seul grand texte (utile pour l'audio). */
export function sectionsEnTexte(sections: SectionCours[]): string {
  return sections
    .map((s) => `${s.titre}.\n${s.lignes.join("\n")}`)
    .join("\n\n");
}
