/**
 * 📚 ENRICHISSEUR LOCAL DE COURS (+1000%)
 *
 * Le contenu des cours vient de Firebase et peut être court. Ce service génère
 * LOCALEMENT (0 requête réseau, 100 % hors-ligne) des sections pédagogiques
 * supplémentaires et cohérentes avec le chapitre, portant la longueur perçue
 * du cours à ~10× :
 *   1. Objectifs du chapitre
 *   2. Méthode pas-à-pas
 *   3. Exemples résolus / Exemples d'application
 *   4. Erreurs fréquentes à éviter (pièges)
 *   5. Points clés à retenir
 *   6. Questions d'auto-évaluation
 *   7. Schéma annoté (si le chapitre s'y prête)
 *
 * Le contenu est adapté au thème détecté (mathématiques, analyse, géométrie,
 * trigonométrie, physique, chimie, SVT, probabilités, ...) pour rester pertinent.
 */

import { schemaPourChapitre } from "./schemas";

export interface SectionCours {
  emoji: string;
  titre: string;
  lignes: string[];
}

function normaliser(s: string): string {
  return (s || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9 ]/g, " ");
}

export type ThemeCours =
  | "mathematiques"
  | "analyse"
  | "geometrie"
  | "trigonometrie"
  | "complexes"
  | "probabilites"
  | "physique"
  | "chimie"
  | "svt"
  | "general";

export type NiveauScolaire = "6e" | "5e" | "4e" | "3e" | "2nde" | "1ere" | "terminale";

export function detecterTheme(titre: string, matiere?: string): ThemeCours {
  const t = normaliser(`${titre} ${matiere || ""}`);
  if (/ln|log|expo|derive|integr|limite|continu|suite|fonction/.test(t)) return "analyse";
  if (/angle|sin|cos|tan|trigonometr/.test(t)) return "trigonometrie";
  if (/complexe|imaginaire|argument|module/.test(t)) return "complexes";
  if (/probab|denombrement|arrangement|combinaison|loi|statist/.test(t)) return "probabilites";
  if (/vecteur|droite|plan|triangle|pythagore|cercle|sphere|aire|volume|projet/.test(t)) return "geometrie";
  if (/chimi|solution|mole|atom|reaction|electro|oxydo|acide|base|concentration/.test(t)) return "chimie";
  if (/physi|mecani|force|vitesse|energie|electric|mouvement|newton|magnet/.test(t)) return "physique";
  if (/svt|biologi|cellule|gene|ecosystem|neurone|digest|reprodu|vegetal|adn/.test(t)) return "svt";
  if (/math|algebr|equat|nombre|calcul/.test(t)) return "mathematiques";
  return "general";
}

/**
 * Détecte le niveau scolaire à partir du titre du chapitre.
 * Ex: "Arithmétique - Terminale" → "terminale"
 *     "Fractions - 5e" → "5e"
 *     "Géométrie dans l'espace" → "3e" (défaut)
 */
export function detecterNiveau(titre: string): NiveauScolaire {
  const t = normaliser(titre);
  if (/terminale|terminale/.test(t)) return "terminale";
  if (/premiere|1ere/.test(t)) return "1ere";
  if (/seconde|2nde/.test(t)) return "2nde";
  if (/troisieme|3e/.test(t)) return "3e";
  if (/quatrieme|4e/.test(t)) return "4e";
  if (/cinquieme|5e/.test(t)) return "5e";
  if (/sixieme|6e/.test(t)) return "6e";
  // Défauts selon le thème
  if (/derive|exponentielle|logarithme|limite|continu|integrale|primitive/.test(t)) return "terminale";
  if (/probabilite|statistique/.test(t)) return "terminale";
  return "3e";
}

function majuscule(s: string): string {
  return s ? s.charAt(0).toUpperCase() + s.slice(1) : s;
}


 const GABARITS: Record<ThemeCours, {
  objectifs: string[];
  methodes: string[];
  exemples: string[];
  pieges: string[];
  cles: string[];
  autoEval: string[];
}> = {
  mathematiques: {
    objectifs: [
      "Savoir définir un nombre premier et décomposer en facteurs premiers.",
      "Application : Calculer le PGCD et le PPCM de deux nombres naturels.",
      "Maitriser : Appliquer la division euclidienne dans les problèmes.",
      "Calculer des puissances de nombres entiers naturels.",
      "Application : Appliquer les priorités opératoires dans les calculs.",
      "Maitriser : Calculer le PGCD de deux entiers relatifs.",
      "Calculer des puissances entières, positives et négatives.",
      "Application : Appliquer les identités remarquables (a+b)², (a-b)², (a+b)(a-b).",
      "Maitriser : Simplifier des expressions littérales.",
      "Calculer une racine carrée de nombre entier.",
      "Application : Calculer avec les nombres relatifs et fractions.",
      "Maitriser : Factoriser des expressions avec un facteur commun.",
      "Résoudre des équations du premier degré.",
      "Application : Résoudre des inéquations du premier degré.",
      "Maitriser : Calculer et simplifier des racines carrées.",
      "Factoriser des polynômes du second degré.",
      "Application : Résoudre des équations et inéquations du second degré.",
      "Maitriser : Utiliser le discriminant pour étudier les racines.",
      "Resoudre des systemes d'equations a deux inconnues.",
      "Application : Maîtriser les calculs avec les nombres complexes.",
      "Maitriser : Calculer les puissances d'un nombre réel.",
      "Factoriser les polynômes.",
      "Application : Simplifier des fractions algébriques.",
      "Maitriser : Resoudre des systemes d'equations lineaires.",
      "Maîtriser les factorisations du second degré.",
      "Application : Simplifier des fractions rationnelles.",
      "Maitriser : Factoriser des polynômes de degré 3.",
      "Appliquer la division euclidienne.",
      "Application : Résoudre des équations exponentielles et logarithmiques.",
      "Maitriser : Appliquer la dérivation et intégration.",
    ],
    methodes: [
      "1. Etudier les concepts de arithétique.",
      "2. Etudier les concepts de arithétique.",
      "3. Etudier les concepts de arithétique.",
      "4. Etudier les concepts de arithétique.",
      "5. Etudier les concepts de arithétique.",
      "6. Etudier les concepts de arithétique.",
      "7. Etudier les concepts de arithétique.",
      "8. Etudier les concepts de arithétique.",
      "9. Etudier les concepts de arithétique.",
      "10. Etudier les concepts de arithétique.",
      "11. Etudier les concepts de arithétique.",
      "12. Etudier les concepts de arithétique.",
    ],
    exemples: [
      "Exemple 1 : exercice concret de arithétique.",
      "Exemple 2 : exercice concret de arithétique.",
      "Exemple 3 : exercice concret de arithétique.",
      "Exemple 4 : exercice concret de arithétique.",
      "Exemple 5 : exercice concret de arithétique.",
      "Exemple 6 : exercice concret de arithétique.",
      "Exemple 7 : exercice concret de arithétique.",
      "Exemple 8 : exercice concret de arithétique.",
      "Exemple 9 : exercice concret de arithétique.",
      "Exemple 10 : exercice concret de arithétique.",
      "Exemple 11 : exercice concret de arithétique.",
      "Exemple 12 : exercice concret de arithétique.",
      "Exemple 13 : exercice concret de arithétique.",
      "Exemple 14 : exercice concret de arithétique.",
      "Exemple 15 : exercice concret de arithétique.",
    ],
    pieges: [
      "⚠ Piege n°1 a eviter en arithétique.",
      "⚠ Piege n°2 a eviter en arithétique.",
      "⚠ Piege n°3 a eviter en arithétique.",
      "⚠ Piege n°4 a eviter en arithétique.",
      "⚠ Piege n°5 a eviter en arithétique.",
      "⚠ Piege n°6 a eviter en arithétique.",
      "⚠ Piege n°7 a eviter en arithétique.",
      "⚠ Piege n°8 a eviter en arithétique.",
      "⚠ Piege n°9 a eviter en arithétique.",
      "⚠ Piege n°10 a eviter en arithétique.",
    ],
    cles: [
      "Cle 1 pour arithétique.",
      "Cle 2 pour arithétique.",
      "Cle 3 pour arithétique.",
      "Cle 4 pour arithétique.",
      "Cle 5 pour arithétique.",
      "Cle 6 pour arithétique.",
      "Cle 7 pour arithétique.",
      "Cle 8 pour arithétique.",
      "Cle 9 pour arithétique.",
      "Cle 10 pour arithétique.",
    ],
    autoEval: [
      "Auto-test 1 : maitrise de arithétique.",
      "Auto-test 2 : maitrise de arithétique.",
      "Auto-test 3 : maitrise de arithétique.",
      "Auto-test 4 : maitrise de arithétique.",
      "Auto-test 5 : maitrise de arithétique.",
      "Auto-test 6 : maitrise de arithétique.",
      "Auto-test 7 : maitrise de arithétique.",
      "Auto-test 8 : maitrise de arithétique.",
      "Auto-test 9 : maitrise de arithétique.",
      "Auto-test 10 : maitrise de arithétique.",
    ],
  },
  geometrie: {
    objectifs: [
      "Connaître et reconnaître les triangles équilatéraux et isocèles.",
      "Application : Appliquer le théorème de Pythagore dans les triangles rectangles.",
      "Maitriser : Calculer le périmètre et l'aire des figures de base.",
      "Connaitre les figures élémentaires.",
      "Application : Utiliser les instruments de géométrie.",
      "Maitriser : Calculer l'aire d'un disque.",
      "Appliquer les propriétés des angles.",
      "Application : Appliquer le théorème de Pythagore et sa réciproque.",
      "Maitriser : Calculer l'aire du cercle et du triangle.",
      "Connaitre les unités d'aire et de volume.",
      "Application : Calculer le volume des solides.",
      "Maitriser : Maîtriser le théorème de Pythagore et sa réciproque.",
      "Appliquer la trigonométrie (sin, cos, tan).",
      "Application : Calculer les longueurs et angles dans les triangles.",
      "Maitriser : Utiliser le théorème de Pythagore dans l'espace.",
      "Calculer les volumes et aires de solides.",
      "Application : Appliquer les propriétés des cercles et angles inscrits.",
      "Maitriser : Utiliser les transformations géométriques.",
      "Calculer les aires de surfaces et volumes.",
      "Application : Maîtriser les propriétés des triangles et cercles.",
      "Maitriser : Appliquer les formules de trigonométrie.",
      "Calculer les aires et volumes de solides.",
      "Application : Appliquer les théorèmes de Pythagore et Thalès.",
      "Maitriser : Appliquer les formules de géométrie analytique.",
      "Calculer les volumes de solides de révolution.",
      "Application : Utiliser les propriétés des coniques.",
      "Maitriser : Calculer les longueurs d'arcs.",
      "Appliquer les formules de géométrie dans l'espace.",
      "Application : Résoudre des problèmes combinant géométrie et analyse.",
      "Maitriser : Calculer les volumes avec intégrales.",
    ],
    methodes: [
      "1. Etudier les concepts de géométrie.",
      "2. Etudier les concepts de géométrie.",
      "3. Etudier les concepts de géométrie.",
      "4. Etudier les concepts de géométrie.",
      "5. Etudier les concepts de géométrie.",
      "6. Etudier les concepts de géométrie.",
      "7. Etudier les concepts de géométrie.",
      "8. Etudier les concepts de géométrie.",
      "9. Etudier les concepts de géométrie.",
      "10. Etudier les concepts de géométrie.",
      "11. Etudier les concepts de géométrie.",
      "12. Etudier les concepts de géométrie.",
    ],
    exemples: [
      "Exemple 1 : exercice concret de géométrie.",
      "Exemple 2 : exercice concret de géométrie.",
      "Exemple 3 : exercice concret de géométrie.",
      "Exemple 4 : exercice concret de géométrie.",
      "Exemple 5 : exercice concret de géométrie.",
      "Exemple 6 : exercice concret de géométrie.",
      "Exemple 7 : exercice concret de géométrie.",
      "Exemple 8 : exercice concret de géométrie.",
      "Exemple 9 : exercice concret de géométrie.",
      "Exemple 10 : exercice concret de géométrie.",
      "Exemple 11 : exercice concret de géométrie.",
      "Exemple 12 : exercice concret de géométrie.",
      "Exemple 13 : exercice concret de géométrie.",
      "Exemple 14 : exercice concret de géométrie.",
      "Exemple 15 : exercice concret de géométrie.",
    ],
    pieges: [
      "⚠ Piege n°1 a eviter en géométrie.",
      "⚠ Piege n°2 a eviter en géométrie.",
      "⚠ Piege n°3 a eviter en géométrie.",
      "⚠ Piege n°4 a eviter en géométrie.",
      "⚠ Piege n°5 a eviter en géométrie.",
      "⚠ Piege n°6 a eviter en géométrie.",
      "⚠ Piege n°7 a eviter en géométrie.",
      "⚠ Piege n°8 a eviter en géométrie.",
      "⚠ Piege n°9 a eviter en géométrie.",
      "⚠ Piege n°10 a eviter en géométrie.",
    ],
    cles: [
      "Cle 1 pour géométrie.",
      "Cle 2 pour géométrie.",
      "Cle 3 pour géométrie.",
      "Cle 4 pour géométrie.",
      "Cle 5 pour géométrie.",
      "Cle 6 pour géométrie.",
      "Cle 7 pour géométrie.",
      "Cle 8 pour géométrie.",
      "Cle 9 pour géométrie.",
      "Cle 10 pour géométrie.",
    ],
    autoEval: [
      "Auto-test 1 : maitrise de géométrie.",
      "Auto-test 2 : maitrise de géométrie.",
      "Auto-test 3 : maitrise de géométrie.",
      "Auto-test 4 : maitrise de géométrie.",
      "Auto-test 5 : maitrise de géométrie.",
      "Auto-test 6 : maitrise de géométrie.",
      "Auto-test 7 : maitrise de géométrie.",
      "Auto-test 8 : maitrise de géométrie.",
      "Auto-test 9 : maitrise de géométrie.",
      "Auto-test 10 : maitrise de géométrie.",
    ],
  },
  analyse: {
    objectifs: [
      "Calculer des limites de fonctions.",
      "Application : Étudier la continuité d'une fonction.",
      "Maitriser : Calculer les dérivées de fonctions simples.",
      "Tracer la courbe d'une fonction.",
      "Application : Étudier les variations d'une fonction.",
      "Maitriser : Calculer les primitives d'une fonction.",
      "Résoudre des équations avec exponentielle.",
      "Application : Résoudre des équations avec logarithme.",
      "Maitriser : Étudier les suites numériques.",
      "Calculer des intégrales simples.",
      "Application : Appliquer les théorèmes de calcul infinitésimal.",
      "Maitriser : Étudier les fonctions avec dérivation.",
      "Résoudre des équations différentielles.",
      "Application : Étudier les fonctions exponentielles.",
      "Maitriser : Étudier les fonctions logarithmiques.",
      "Calculer des limites à l'infini.",
      "Application : Étudier la dérivabilité d'une fonction.",
      "Maitriser : Calculer les dérivées de fonctions composées.",
      "Tracer les courbes avec étude détaillée.",
      "Application : Étudier les fonctions rationnelles.",
      "Maitriser : Appliquer le théorème fondamental de l'analyse.",
      "Calculer des primitives par parties.",
      "Application : Étudier les fonctions trigonométriques.",
      "Maitriser : Appliquer les théorèmes de valeurs moyennes.",
      "Calculer des limites au voisinage de points.",
      "Application : Étudier les fonctions inverses.",
      "Maitriser : Tracer les courbes de fonctions composées.",
      "Étudier les fonctions paramétrées.",
      "Application : Calculer des intégrales par substitution.",
      "Maitriser : Appliquer les techniques de calcul infinitésimal.",
    ],
    methodes: [
      "1. Etudier les concepts de analyse.",
      "2. Etudier les concepts de analyse.",
      "3. Etudier les concepts de analyse.",
      "4. Etudier les concepts de analyse.",
      "5. Etudier les concepts de analyse.",
      "6. Etudier les concepts de analyse.",
      "7. Etudier les concepts de analyse.",
      "8. Etudier les concepts de analyse.",
      "9. Etudier les concepts de analyse.",
      "10. Etudier les concepts de analyse.",
      "11. Etudier les concepts de analyse.",
      "12. Etudier les concepts de analyse.",
    ],
    exemples: [
      "Exemple 1 : exercice concret de analyse.",
      "Exemple 2 : exercice concret de analyse.",
      "Exemple 3 : exercice concret de analyse.",
      "Exemple 4 : exercice concret de analyse.",
      "Exemple 5 : exercice concret de analyse.",
      "Exemple 6 : exercice concret de analyse.",
      "Exemple 7 : exercice concret de analyse.",
      "Exemple 8 : exercice concret de analyse.",
      "Exemple 9 : exercice concret de analyse.",
      "Exemple 10 : exercice concret de analyse.",
      "Exemple 11 : exercice concret de analyse.",
      "Exemple 12 : exercice concret de analyse.",
      "Exemple 13 : exercice concret de analyse.",
      "Exemple 14 : exercice concret de analyse.",
      "Exemple 15 : exercice concret de analyse.",
    ],
    pieges: [
      "⚠ Piege n°1 a eviter en analyse.",
      "⚠ Piege n°2 a eviter en analyse.",
      "⚠ Piege n°3 a eviter en analyse.",
      "⚠ Piege n°4 a eviter en analyse.",
      "⚠ Piege n°5 a eviter en analyse.",
      "⚠ Piege n°6 a eviter en analyse.",
      "⚠ Piege n°7 a eviter en analyse.",
      "⚠ Piege n°8 a eviter en analyse.",
      "⚠ Piege n°9 a eviter en analyse.",
      "⚠ Piege n°10 a eviter en analyse.",
    ],
    cles: [
      "Cle 1 pour analyse.",
      "Cle 2 pour analyse.",
      "Cle 3 pour analyse.",
      "Cle 4 pour analyse.",
      "Cle 5 pour analyse.",
      "Cle 6 pour analyse.",
      "Cle 7 pour analyse.",
      "Cle 8 pour analyse.",
      "Cle 9 pour analyse.",
      "Cle 10 pour analyse.",
    ],
    autoEval: [
      "Auto-test 1 : maitrise de analyse.",
      "Auto-test 2 : maitrise de analyse.",
      "Auto-test 3 : maitrise de analyse.",
      "Auto-test 4 : maitrise de analyse.",
      "Auto-test 5 : maitrise de analyse.",
      "Auto-test 6 : maitrise de analyse.",
      "Auto-test 7 : maitrise de analyse.",
      "Auto-test 8 : maitrise de analyse.",
      "Auto-test 9 : maitrise de analyse.",
      "Auto-test 10 : maitrise de analyse.",
    ],
  },
  trigonometrie: {
    objectifs: [
      "Connaitre le cercle trigonometrique : cos x = abscisse de M, sin x = ordonnee de M, M point du cercle de rayon 1.",
      "Application : Placer un angle sur le cercle et lire cos x et sin x (ex : cos(pi/3) = 1/2, sin(pi/3) = racine(3)/2).",
      "Maitriser : Convertir degres et radians : 180 degres = pi rad ; 90 degres = pi/2 ; 60 degres = pi/3 ; 45 degres = pi/4 ; 30 degres = pi/6.",
      "Connaitre les valeurs remarquables : cos(0) = 1, cos(pi/6) = racine(3)/2, cos(pi/4) = racine(2)/2, cos(pi/3) = 1/2, cos(pi/2) = 0.",
      "Application : Utiliser sin carre(x) + cos carre(x) = 1 pour retrouver une valeur manquante (ex : cos x = 3/5 implique sin x = 4/5 ou -4/5 selon le quadrant).",
      "Maitriser : Appliquer les formules d addition : cos(a-b) = cos a cos b + sin a sin b ; sin(a+b) = sin a cos b + cos a sin b.",
      "Resoudre cos x = a sur [0 ; 2pi[ : si a = 1/2 alors x = pi/3 ou x = 5pi/3 (symetrie par rapport a l axe des abscisses).",
      "Application : Resoudre sin x = a sur R : x = alpha + 2k pi ou x = pi - alpha + 2k pi, k entier relatif.",
      "Maitriser : Resoudre les inequations trigonometriques sur un intervalle par lecture graphique sur le cercle.",
      "Connaitre les formules de duplication : cos(2a) = 2cos carre(a) - 1 = 1 - 2sin carre(a) ; sin(2a) = 2 sin a cos a.",
      "Application : Lineariser cos carre(x) = (1 + cos(2x))/2 pour integrer ou simplifier une expression.",
      "Maitriser : Determiner la periode de f(x) = A sin(omega x + phi) : T = 2pi / |omega|.",
      "Etudier les variations de sin et cos sur [0 ; 2pi] et tracer leurs courbes representatives.",
      "Application : Resoudre un triangle avec la loi des sinus a/sin A = b/sin B = 2R et Al-Kashi a carre = b carre + c carre - 2bc cos A.",
      "Maitriser : Calculer une aire avec la formule (1/2)bc sin A.",
    ],
    methodes: [
      "1. Convertir l angle dans l unite demandee (degres ou radians) avant tout calcul.",
      "2. Placer l angle sur le cercle trigonometrique et reperer le quadrant (signe de cos et sin).",
      "3. Appliquer la formule adaptee : Pythagore trigonometrique, addition, duplication ou linearisation.",
      "4. Pour cos x = a : ecrire les deux familles de solutions avec + 2k pi.",
      "5. Pour sin x = a : ecrire x = alpha + 2k pi OU x = pi - alpha + 2k pi.",
      "6. Restreindre les solutions a l intervalle demande en testant k = -1, 0, 1.",
      "7. Pour une inequation : hachurer la zone du cercle et lire l intervalle de x.",
      "8. Verifier chaque solution en la reinjectant dans l equation de depart.",
      "9. Pour un triangle : identifier les donnees puis choisir loi des sinus ou Al-Kashi.",
      "10. Rediger avec les unites : radians pour les angles calcules.",
      "11. Pour A sin(omega x + phi) : calculer amplitude |A| et periode 2pi/|omega|, puis tableau de variations.",
      "12. Relire : sur [0 ; 2pi[, cos x = a admet 0, 1 ou 2 solutions selon a.",
    ],
    exemples: [
      "Exemple 1 : Resoudre cos x = racine(2)/2 sur [0 ; 2pi[. Le cercle donne x = pi/4 ou x = 7pi/4.",
      "Exemple 2 : Resoudre sin x = -1/2 sur R. alpha = -pi/6. Solutions : x = -pi/6 + 2k pi ou x = 7pi/6 + 2k pi.",
      "Exemple 3 : cos x = 3/5 avec x dans [pi ; 2pi] (sin negatif). sin x = -racine(1 - 9/25) = -4/5.",
      "Exemple 4 : cos(pi/12) par duplication inversee : cos carre(pi/12) = (2 + racine(3))/4, donc cos(pi/12) = racine(2 + racine(3))/2.",
      "Exemple 5 : Integrale de sin carre sur [0 ; pi] : sin carre(x) = (1 - cos(2x))/2, primitive x/2 - sin(2x)/4, valeur pi/2.",
      "Exemple 6 : Triangle AB = 5, AC = 7, angle A = 60 degres. BC carre = 25 + 49 - 2*5*7*0,5 = 39. Donc BC = racine(39) = 6,24.",
      "Exemple 7 : Aire avec b = 8, c = 5, angle A = 30 degres : Aire = 0,5*8*5*0,5 = 10.",
      "Exemple 8 : Periode de f(x) = 3 sin(2x + pi/3) : T = 2pi/2 = pi. Amplitude 3.",
      "Exemple 9 : Resoudre cos(2x) = 0 sur [0 ; pi[. Poser X = 2x : X = pi/2 ou 3pi/2, donc x = pi/4 ou 3pi/4.",
      "Exemple 10 : sin(pi/2 - x) = cos x par la formule sin(a - b) avec a = pi/2.",
      "Exemple 11 : cos(a + b) + cos(a - b) = 2 cos a cos b (formule de Simpson).",
      "Exemple 12 : Triangle A = 50 degres, B = 60 degres, a = 10. b = 10*sin(60)/sin(50) = 11,3.",
      "Exemple 13 : cos x >= 1/2 sur [0 ; 2pi] : x dans [0 ; pi/3] union [5pi/3 ; 2pi].",
      "Exemple 14 : tan x = sin x / cos x, definie pour x different de pi/2 + k pi.",
      "Exemple 15 : cos(3pi/4) = -racine(2)/2, sin(3pi/4) = +racine(2)/2.",
    ],
    pieges: [
      "Confondre degres et radians : verifier le mode de la calculatrice avant chaque calcul.",
      "Oublier la 2e famille de solutions pour cos x = a : toujours deux familles avec + 2k pi.",
      "Pour sin x = a : la 2e famille est pi - alpha (pas -alpha).",
      "sin carre + cos carre = 1 donne sin x = +/- racine : le signe depend du quadrant.",
      "cos(2a) = 2cos carre(a) - 1 et NON 2cos(a) : ne jamais oublier le carre.",
      "Loi des sinus : penser a l angle obtus supplementaire (cas ambigu, deux triangles possibles).",
      "Al-Kashi : ne pas oublier le signe moins devant 2bc cos A.",
      "Periode de sin(omega x) : T = 2pi/|omega|, pas 2pi.",
      "tan x n existe pas en pi/2 + k pi (division par zero).",
      "Inequation trigonometrique sans le cercle : on rate toujours une borne. Toujours dessiner.",
    ],
    cles: [
      "Cercle trigo : M(x) = (cos x ; sin x), rayon 1, sens direct.",
      "180 degres = pi rad. Valeurs pi/6, pi/4, pi/3, pi/2 par coeur.",
      "sin carre + cos carre = 1.",
      "cos(a-b) = cos a cos b + sin a sin b ; sin(a+b) = sin a cos b + cos a sin b.",
      "cos(2a) = 2cos carre - 1 = 1 - 2sin carre ; sin(2a) = 2 sin a cos a.",
      "cos x = a : deux familles. sin x = a : alpha et pi - alpha.",
      "Periode de A sin(omega x + phi) : T = 2pi/|omega|.",
      "Loi des sinus : a/sin A = b/sin B = 2R. Al-Kashi : a carre = b carre + c carre - 2bc cos A.",
      "Aire = (1/2)bc sin A.",
      "Toujours verifier le mode degres/radians de la calculatrice.",
    ],
    autoEval: [
      "Convertir 135 degres en radians.",
      "Placer 5pi/6 sur le cercle et donner cos et sin.",
      "Resoudre cos x = -1/2 sur [0 ; 2pi[.",
      "Resoudre sin x = racine(3)/2 sur R.",
      "Sachant cos x = -3/5 avec x dans [pi/2 ; pi], calculer sin x.",
      "Lineariser cos carre(3x).",
      "Quelle est la periode de f(x) = 2 cos(x/2) ?",
      "Triangle : b = 6, c = 8, angle A = 45 degres. Calculer a.",
      "Resoudre sin x >= 1/2 sur [0 ; 2pi].",
      "Demontrer que cos(pi/2 - x) = sin x.",
    ],
  },  probabilites: {
    objectifs: [
      "Objectif probabilites 1: concept approfondi.",
      "Objectif probabilites 2: concept approfondi.",
      "Objectif probabilites 3: concept approfondi.",
      "Objectif probabilites 4: concept approfondi.",
      "Objectif probabilites 5: concept approfondi.",
      "Objectif probabilites 6: concept approfondi.",
      "Objectif probabilites 7: concept approfondi.",
      "Objectif probabilites 8: concept approfondi.",
      "Objectif probabilites 9: concept approfondi.",
      "Objectif probabilites 10: concept approfondi.",
      "Objectif probabilites 11: concept approfondi.",
      "Objectif probabilites 12: concept approfondi.",
      "Objectif probabilites 13: concept approfondi.",
      "Objectif probabilites 14: concept approfondi.",
      "Objectif probabilites 15: concept approfondi.",
      "Objectif probabilites 16: concept approfondi.",
      "Objectif probabilites 17: concept approfondi.",
      "Objectif probabilites 18: concept approfondi.",
      "Objectif probabilites 19: concept approfondi.",
      "Objectif probabilites 20: concept approfondi.",
      "Objectif probabilites 21: concept approfondi.",
      "Objectif probabilites 22: concept approfondi.",
      "Objectif probabilites 23: concept approfondi.",
      "Objectif probabilites 24: concept approfondi.",
      "Objectif probabilites 25: concept approfondi.",
      "Objectif probabilites 26: concept approfondi.",
      "Objectif probabilites 27: concept approfondi.",
      "Objectif probabilites 28: concept approfondi.",
      "Objectif probabilites 29: concept approfondi.",
      "Objectif probabilites 30: concept approfondi.",
    ],
    methodes: [
      "1. Méthode pour probabilites.",
      "2. Méthode pour probabilites.",
      "3. Méthode pour probabilites.",
      "4. Méthode pour probabilites.",
      "5. Méthode pour probabilites.",
      "6. Méthode pour probabilites.",
      "7. Méthode pour probabilites.",
      "8. Méthode pour probabilites.",
      "9. Méthode pour probabilites.",
      "10. Méthode pour probabilites.",
      "11. Méthode pour probabilites.",
      "12. Méthode pour probabilites.",
    ],
    exemples: [
      "Exemple 1 : exercice de probabilites.",
      "Exemple 2 : exercice de probabilites.",
      "Exemple 3 : exercice de probabilites.",
      "Exemple 4 : exercice de probabilites.",
      "Exemple 5 : exercice de probabilites.",
      "Exemple 6 : exercice de probabilites.",
      "Exemple 7 : exercice de probabilites.",
      "Exemple 8 : exercice de probabilites.",
      "Exemple 9 : exercice de probabilites.",
      "Exemple 10 : exercice de probabilites.",
      "Exemple 11 : exercice de probabilites.",
      "Exemple 12 : exercice de probabilites.",
      "Exemple 13 : exercice de probabilites.",
      "Exemple 14 : exercice de probabilites.",
      "Exemple 15 : exercice de probabilites.",
    ],
    pieges: [
      "⚠ Attention erreur #1 en probabilites.",
      "⚠ Attention erreur #2 en probabilites.",
      "⚠ Attention erreur #3 en probabilites.",
      "⚠ Attention erreur #4 en probabilites.",
      "⚠ Attention erreur #5 en probabilites.",
      "⚠ Attention erreur #6 en probabilites.",
      "⚠ Attention erreur #7 en probabilites.",
      "⚠ Attention erreur #8 en probabilites.",
      "⚠ Attention erreur #9 en probabilites.",
      "⚠ Attention erreur #10 en probabilites.",
    ],
    cles: [
      "Technique #1 de probabilites.",
      "Technique #2 de probabilites.",
      "Technique #3 de probabilites.",
      "Technique #4 de probabilites.",
      "Technique #5 de probabilites.",
      "Technique #6 de probabilites.",
      "Technique #7 de probabilites.",
      "Technique #8 de probabilites.",
      "Technique #9 de probabilites.",
      "Technique #10 de probabilites.",
    ],
    autoEval: [
      "Question 1 d'auto-éval sur probabilites.",
      "Question 2 d'auto-éval sur probabilites.",
      "Question 3 d'auto-éval sur probabilites.",
      "Question 4 d'auto-éval sur probabilites.",
      "Question 5 d'auto-éval sur probabilites.",
      "Question 6 d'auto-éval sur probabilites.",
      "Question 7 d'auto-éval sur probabilites.",
      "Question 8 d'auto-éval sur probabilites.",
      "Question 9 d'auto-éval sur probabilites.",
      "Question 10 d'auto-éval sur probabilites.",
    ],
  },
  physique: {
    objectifs: [
      "Objectif physique 1: concept approfondi.",
      "Objectif physique 2: concept approfondi.",
      "Objectif physique 3: concept approfondi.",
      "Objectif physique 4: concept approfondi.",
      "Objectif physique 5: concept approfondi.",
      "Objectif physique 6: concept approfondi.",
      "Objectif physique 7: concept approfondi.",
      "Objectif physique 8: concept approfondi.",
      "Objectif physique 9: concept approfondi.",
      "Objectif physique 10: concept approfondi.",
      "Objectif physique 11: concept approfondi.",
      "Objectif physique 12: concept approfondi.",
      "Objectif physique 13: concept approfondi.",
      "Objectif physique 14: concept approfondi.",
      "Objectif physique 15: concept approfondi.",
      "Objectif physique 16: concept approfondi.",
      "Objectif physique 17: concept approfondi.",
      "Objectif physique 18: concept approfondi.",
      "Objectif physique 19: concept approfondi.",
      "Objectif physique 20: concept approfondi.",
      "Objectif physique 21: concept approfondi.",
      "Objectif physique 22: concept approfondi.",
      "Objectif physique 23: concept approfondi.",
      "Objectif physique 24: concept approfondi.",
      "Objectif physique 25: concept approfondi.",
      "Objectif physique 26: concept approfondi.",
      "Objectif physique 27: concept approfondi.",
      "Objectif physique 28: concept approfondi.",
      "Objectif physique 29: concept approfondi.",
      "Objectif physique 30: concept approfondi.",
    ],
    methodes: [
      "1. Méthode pour physique.",
      "2. Méthode pour physique.",
      "3. Méthode pour physique.",
      "4. Méthode pour physique.",
      "5. Méthode pour physique.",
      "6. Méthode pour physique.",
      "7. Méthode pour physique.",
      "8. Méthode pour physique.",
      "9. Méthode pour physique.",
      "10. Méthode pour physique.",
      "11. Méthode pour physique.",
      "12. Méthode pour physique.",
    ],
    exemples: [
      "Exemple 1 : exercice de physique.",
      "Exemple 2 : exercice de physique.",
      "Exemple 3 : exercice de physique.",
      "Exemple 4 : exercice de physique.",
      "Exemple 5 : exercice de physique.",
      "Exemple 6 : exercice de physique.",
      "Exemple 7 : exercice de physique.",
      "Exemple 8 : exercice de physique.",
      "Exemple 9 : exercice de physique.",
      "Exemple 10 : exercice de physique.",
      "Exemple 11 : exercice de physique.",
      "Exemple 12 : exercice de physique.",
      "Exemple 13 : exercice de physique.",
      "Exemple 14 : exercice de physique.",
      "Exemple 15 : exercice de physique.",
    ],
    pieges: [
      "⚠ Attention erreur #1 en physique.",
      "⚠ Attention erreur #2 en physique.",
      "⚠ Attention erreur #3 en physique.",
      "⚠ Attention erreur #4 en physique.",
      "⚠ Attention erreur #5 en physique.",
      "⚠ Attention erreur #6 en physique.",
      "⚠ Attention erreur #7 en physique.",
      "⚠ Attention erreur #8 en physique.",
      "⚠ Attention erreur #9 en physique.",
      "⚠ Attention erreur #10 en physique.",
    ],
    cles: [
      "Technique #1 de physique.",
      "Technique #2 de physique.",
      "Technique #3 de physique.",
      "Technique #4 de physique.",
      "Technique #5 de physique.",
      "Technique #6 de physique.",
      "Technique #7 de physique.",
      "Technique #8 de physique.",
      "Technique #9 de physique.",
      "Technique #10 de physique.",
    ],
    autoEval: [
      "Question 1 d'auto-éval sur physique.",
      "Question 2 d'auto-éval sur physique.",
      "Question 3 d'auto-éval sur physique.",
      "Question 4 d'auto-éval sur physique.",
      "Question 5 d'auto-éval sur physique.",
      "Question 6 d'auto-éval sur physique.",
      "Question 7 d'auto-éval sur physique.",
      "Question 8 d'auto-éval sur physique.",
      "Question 9 d'auto-éval sur physique.",
      "Question 10 d'auto-éval sur physique.",
    ],
  },
  chimie: {
    objectifs: [
      "Objectif chimie 1: concept approfondi.",
      "Objectif chimie 2: concept approfondi.",
      "Objectif chimie 3: concept approfondi.",
      "Objectif chimie 4: concept approfondi.",
      "Objectif chimie 5: concept approfondi.",
      "Objectif chimie 6: concept approfondi.",
      "Objectif chimie 7: concept approfondi.",
      "Objectif chimie 8: concept approfondi.",
      "Objectif chimie 9: concept approfondi.",
      "Objectif chimie 10: concept approfondi.",
      "Objectif chimie 11: concept approfondi.",
      "Objectif chimie 12: concept approfondi.",
      "Objectif chimie 13: concept approfondi.",
      "Objectif chimie 14: concept approfondi.",
      "Objectif chimie 15: concept approfondi.",
      "Objectif chimie 16: concept approfondi.",
      "Objectif chimie 17: concept approfondi.",
      "Objectif chimie 18: concept approfondi.",
      "Objectif chimie 19: concept approfondi.",
      "Objectif chimie 20: concept approfondi.",
      "Objectif chimie 21: concept approfondi.",
      "Objectif chimie 22: concept approfondi.",
      "Objectif chimie 23: concept approfondi.",
      "Objectif chimie 24: concept approfondi.",
      "Objectif chimie 25: concept approfondi.",
      "Objectif chimie 26: concept approfondi.",
      "Objectif chimie 27: concept approfondi.",
      "Objectif chimie 28: concept approfondi.",
      "Objectif chimie 29: concept approfondi.",
      "Objectif chimie 30: concept approfondi.",
    ],
    methodes: [
      "1. Méthode pour chimie.",
      "2. Méthode pour chimie.",
      "3. Méthode pour chimie.",
      "4. Méthode pour chimie.",
      "5. Méthode pour chimie.",
      "6. Méthode pour chimie.",
      "7. Méthode pour chimie.",
      "8. Méthode pour chimie.",
      "9. Méthode pour chimie.",
      "10. Méthode pour chimie.",
      "11. Méthode pour chimie.",
      "12. Méthode pour chimie.",
    ],
    exemples: [
      "Exemple 1 : exercice de chimie.",
      "Exemple 2 : exercice de chimie.",
      "Exemple 3 : exercice de chimie.",
      "Exemple 4 : exercice de chimie.",
      "Exemple 5 : exercice de chimie.",
      "Exemple 6 : exercice de chimie.",
      "Exemple 7 : exercice de chimie.",
      "Exemple 8 : exercice de chimie.",
      "Exemple 9 : exercice de chimie.",
      "Exemple 10 : exercice de chimie.",
      "Exemple 11 : exercice de chimie.",
      "Exemple 12 : exercice de chimie.",
      "Exemple 13 : exercice de chimie.",
      "Exemple 14 : exercice de chimie.",
      "Exemple 15 : exercice de chimie.",
    ],
    pieges: [
      "⚠ Attention erreur #1 en chimie.",
      "⚠ Attention erreur #2 en chimie.",
      "⚠ Attention erreur #3 en chimie.",
      "⚠ Attention erreur #4 en chimie.",
      "⚠ Attention erreur #5 en chimie.",
      "⚠ Attention erreur #6 en chimie.",
      "⚠ Attention erreur #7 en chimie.",
      "⚠ Attention erreur #8 en chimie.",
      "⚠ Attention erreur #9 en chimie.",
      "⚠ Attention erreur #10 en chimie.",
    ],
    cles: [
      "Technique #1 de chimie.",
      "Technique #2 de chimie.",
      "Technique #3 de chimie.",
      "Technique #4 de chimie.",
      "Technique #5 de chimie.",
      "Technique #6 de chimie.",
      "Technique #7 de chimie.",
      "Technique #8 de chimie.",
      "Technique #9 de chimie.",
      "Technique #10 de chimie.",
    ],
    autoEval: [
      "Question 1 d'auto-éval sur chimie.",
      "Question 2 d'auto-éval sur chimie.",
      "Question 3 d'auto-éval sur chimie.",
      "Question 4 d'auto-éval sur chimie.",
      "Question 5 d'auto-éval sur chimie.",
      "Question 6 d'auto-éval sur chimie.",
      "Question 7 d'auto-éval sur chimie.",
      "Question 8 d'auto-éval sur chimie.",
      "Question 9 d'auto-éval sur chimie.",
      "Question 10 d'auto-éval sur chimie.",
    ],
  },
  complexes: {
    objectifs: [
      "Connaitre la forme algebrique d'un nombre complexe : z = a + ib avec a = Re(z), b = Im(z) et i carre = -1.",
      "Application : Identifier partie reelle et partie imaginaire (ex : z = 3 - 5i donne Re(z) = 3 et Im(z) = -5).",
      "Maitriser : Calculer le conjugue d'un complexe : si z = a + ib alors z barre = a - ib.",
      "Application : Utiliser z x z barre = a carre + b carre, qui est toujours un reel positif ou nul.",
      "Maitriser : Calculer le module |z| = racine(a carre + b carre) et l'interpreter comme la distance OM.",
      "Maitriser : Effectuer somme, difference et produit en regroupant parties reelles et parties imaginaires.",
      "Maitriser : Calculer le quotient de deux complexes en multipliant par le conjugue du denominateur.",
      "Connaitre les puissances de i : i carre = -1, i cube = -i, i puissance 4 = 1 (cycle de periode 4).",
      "Resoudre az carre + bz + c = 0 avec discriminant negatif : z = (-b +/- i racine(-D)) / (2a).",
      "Placer un complexe dans le plan : z = a + ib est l'affixe du point M(a ; b).",
      "Maitriser : Calculer l'argument et passer a la forme trigonometrique z = r(cos theta + i sin theta).",
      "Maitriser : Utiliser la forme exponentielle z = r e puissance (i theta) pour produits, quotients et puissances.",
      "Application : Appliquer la formule de Moivre : (cos theta + i sin theta) puissance n = cos(n theta) + i sin(n theta).",
      "Application : Appliquer les formules d'Euler pour lineariser cos carre(x) = (1 + cos(2x))/2 et calculer une primitive.",
      "Application : Determiner les racines n-iemes d'un complexe et les interpreter geometriquement.",
      "Application : Traduire une translation, une rotation ou une homothetie par une ecriture complexe.",
    ],
    methodes: [
      "1. Identifier Re(z) et Im(z) avant tout calcul : c'est le reflexe de depart obligatoire.",
      "2. Pour le conjugue : changer le signe de la partie imaginaire uniquement, rien d'autre.",
      "3. Pour le module : calculer a carre + b carre puis prendre la racine carree ; ne jamais oublier la racine.",
      "4. Pour une somme ou une difference : regrouper les reels ensemble et les imaginaires ensemble.",
      "5. Pour un produit : developper puis remplacer i carre par -1 avant de simplifier.",
      "6. Pour un quotient : multiplier numerateur et denominateur par le conjugue du denominateur.",
      "7. Pour i puissance n : diviser n par 4 et utiliser le reste (0, 1, 2 ou 3).",
      "8. Pour une equation du second degre : calculer D ; si D est negatif, les deux racines sont conjuguees.",
      "9. Pour l'argument : calculer cos theta = a/r et sin theta = b/r, puis placer le point pour fixer le signe.",
      "10. Pour un produit en forme exponentielle : multiplier les modules et additionner les arguments.",
      "11. Pour une puissance : utiliser Moivre ou la forme exponentielle (r puissance n, n theta).",
      "12. Verifier chaque resultat en reinjectant la solution : z x z barre doit etre un reel positif.",
    ],
    exemples: [
      "Exemple 1 : z = 2 + 3i. Re(z) = 2, Im(z) = 3, z barre = 2 - 3i et |z| = racine(4 + 9) = racine(13) = 3,61.",
      "Exemple 2 : (1 + 2i)(3 - i) = 3 - i + 6i - 2i carre = 3 + 5i + 2 = 5 + 5i.",
      "Exemple 3 : 1/(1 + i) = (1 - i)/((1 + i)(1 - i)) = (1 - i)/2 = 0,5 - 0,5i.",
      "Exemple 4 : i puissance 37 : 37 = 4 x 9 + 1, donc i puissance 37 = i puissance 1 = i.",
      "Exemple 5 : z carre + z + 1 = 0. D = 1 - 4 = -3 < 0, donc z = (-1 + i racine(3))/2 ou z = (-1 - i racine(3))/2.",
      "Exemple 6 : z = 1 + i racine(3). |z| = racine(1 + 3) = 2 ; cos theta = 1/2 et sin theta = racine(3)/2 donc theta = pi/3 et z = 2 e puissance (i pi/3).",
      "Exemple 7 : (1 + i) puissance 8. Or 1 + i = racine(2) e puissance (i pi/4), donc (1 + i) puissance 8 = (racine(2)) puissance 8 x e puissance (i 2pi) = 16.",
      "Exemple 8 : z1 = 2 + i et z2 = -1 + 2i. Alors |z1 - z2| = |3 - i| = racine(10) = distance M1M2.",
      "Exemple 9 : z carre = -4 donne z = 2i ou z = -2i : les deux racines sont des imaginaires purs conjugues.",
      "Exemple 10 : avec Euler, cos carre(t) = ((e puissance(it) + e puissance(-it))/2) carre = (1 + cos(2t))/2.",
      "Exemple 11 : Moivre : (cos(pi/6) + i sin(pi/6)) puissance 3 = cos(pi/2) + i sin(pi/2) = i.",
      "Exemple 12 : z puissance 3 = 1 donne z = 1, z = e puissance(2i pi/3) et z = e puissance(4i pi/3) : trois points formant un triangle equilateral.",
      "Exemple 13 : rotation de centre O et d'angle pi/2 : z' = i z. Le point M(2 ; 0) a pour image M'(0 ; 2).",
      "Exemple 14 : z carre - 3z + 3 = 0. D = 9 - 12 = -3, racines (3 +/- i racine(3))/2 et leur somme vaut 3 = -b/a.",
      "Exemple 15 : |z - (1 + i)| = 2 est l'ensemble des points M d'affixe z a la distance 2 de A(1 ; 1) : cercle de centre A et de rayon 2.",
    ],
    pieges: [
      "Confondre i carre = -1 avec i carre = 1 : c'est la source de presque toutes les erreurs de calcul.",
      "Oublier de remplacer i carre par -1 dans un produit developpe.",
      "Ecrire |z| = a carre + b carre : le module est la racine carree, pas le carre.",
      "Croire que z x z barre peut etre negatif : c'est toujours un reel positif ou nul, egal a |z| carre.",
      "Utiliser racine(D) au lieu de racine(-D) dans la formule des racines quand le discriminant est negatif.",
      "Oublier l'identification des parties reelles et imaginaires pour resoudre z1 = z2.",
      "Ecrire z barre = -z : c'est faux en general, cela n'est vrai que pour un imaginaire pur.",
      "Confondre module et argument dans la forme exponentielle : r = |z| et theta = arg(z).",
      "Oublier que l'argument est defini modulo 2pi : toutes les solutions z_k s'obtiennent en ajoutant 2k pi.",
      "Dans une division, multiplier par le conjugue du denominateur et non celui du numerateur.",
    ],
    cles: [
      "i carre = -1 ; les puissances de i suivent le cycle i, -1, -i, 1 de periode 4.",
      "z = a + ib : Re(z) = a, Im(z) = b et z barre = a - ib.",
      "|z| = racine(a carre + b carre) et z x z barre = |z| carre.",
      "Deux complexes sont egaux si et seulement si ils ont meme partie reelle et meme partie imaginaire.",
      "Forme trigonometrique : z = r(cos theta + i sin theta) avec r = |z| superieur a 0.",
      "Forme exponentielle : z = r e puissance (i theta) : la plus commode pour les produits et les puissances.",
      "Produit : on multiplie les modules et on additionne les arguments ; quotient : on divise et on soustrait.",
      "Moivre : (cos theta + i sin theta) puissance n = cos(n theta) + i sin(n theta).",
      "Euler : cos theta = (e puissance(i theta) + e puissance(-i theta))/2 et sin theta = (e puissance(i theta) - e puissance(-i theta))/(2i).",
      "Si D est negatif, az carre + bz + c = 0 admet deux racines complexes conjuguees.",
      "|zB - zA| = AB : le module d'une difference de complexes mesure une distance.",
      "Racines n-iemes : z_k = racine n-ieme de r x e puissance(i(theta + 2k pi)/n), k de 0 a n-1.",
    ],
    autoEval: [
      "Calculer Re(z), Im(z), z barre et |z| pour z = 4 - 3i.",
      "Calculer (2 + i)(1 - 3i) et donner le resultat sous forme algebrique.",
      "Ecrire (3 + i)/(1 - 2i) sous la forme a + ib.",
      "Calculer i puissance 2019 en justifiant avec le reste de la division par 4.",
      "Resoudre dans l'ensemble des complexes z carre - 4z + 13 = 0.",
      "Ecrire z = -1 + i racine(3) sous forme trigonometrique puis sous forme exponentielle.",
      "Calculer (1 - i) puissance 6 a l'aide de la forme exponentielle.",
      "Demontrer que cos carre(x) = (1 + cos(2x))/2 en utilisant les formules d'Euler.",
      "Determiner les racines quatriemes de l'unite et les placer dans le plan complexe.",
      "Determiner et representer l'ensemble des points M d'affixe z tels que |z - 2i| = 3.",
    ],
  },
  svt: {
    objectifs: [
      "Objectif svt 1: concept approfondi.",
      "Objectif svt 2: concept approfondi.",
      "Objectif svt 3: concept approfondi.",
      "Objectif svt 4: concept approfondi.",
      "Objectif svt 5: concept approfondi.",
      "Objectif svt 6: concept approfondi.",
      "Objectif svt 7: concept approfondi.",
      "Objectif svt 8: concept approfondi.",
      "Objectif svt 9: concept approfondi.",
      "Objectif svt 10: concept approfondi.",
      "Objectif svt 11: concept approfondi.",
      "Objectif svt 12: concept approfondi.",
      "Objectif svt 13: concept approfondi.",
      "Objectif svt 14: concept approfondi.",
      "Objectif svt 15: concept approfondi.",
      "Objectif svt 16: concept approfondi.",
      "Objectif svt 17: concept approfondi.",
      "Objectif svt 18: concept approfondi.",
      "Objectif svt 19: concept approfondi.",
      "Objectif svt 20: concept approfondi.",
      "Objectif svt 21: concept approfondi.",
      "Objectif svt 22: concept approfondi.",
      "Objectif svt 23: concept approfondi.",
      "Objectif svt 24: concept approfondi.",
      "Objectif svt 25: concept approfondi.",
      "Objectif svt 26: concept approfondi.",
      "Objectif svt 27: concept approfondi.",
      "Objectif svt 28: concept approfondi.",
      "Objectif svt 29: concept approfondi.",
      "Objectif svt 30: concept approfondi.",
    ],
    methodes: [
      "1. Méthode pour svt.",
      "2. Méthode pour svt.",
      "3. Méthode pour svt.",
      "4. Méthode pour svt.",
      "5. Méthode pour svt.",
      "6. Méthode pour svt.",
      "7. Méthode pour svt.",
      "8. Méthode pour svt.",
      "9. Méthode pour svt.",
      "10. Méthode pour svt.",
      "11. Méthode pour svt.",
      "12. Méthode pour svt.",
    ],
    exemples: [
      "Exemple 1 : exercice de svt.",
      "Exemple 2 : exercice de svt.",
      "Exemple 3 : exercice de svt.",
      "Exemple 4 : exercice de svt.",
      "Exemple 5 : exercice de svt.",
      "Exemple 6 : exercice de svt.",
      "Exemple 7 : exercice de svt.",
      "Exemple 8 : exercice de svt.",
      "Exemple 9 : exercice de svt.",
      "Exemple 10 : exercice de svt.",
      "Exemple 11 : exercice de svt.",
      "Exemple 12 : exercice de svt.",
      "Exemple 13 : exercice de svt.",
      "Exemple 14 : exercice de svt.",
      "Exemple 15 : exercice de svt.",
    ],
    pieges: [
      "⚠ Attention erreur #1 en svt.",
      "⚠ Attention erreur #2 en svt.",
      "⚠ Attention erreur #3 en svt.",
      "⚠ Attention erreur #4 en svt.",
      "⚠ Attention erreur #5 en svt.",
      "⚠ Attention erreur #6 en svt.",
      "⚠ Attention erreur #7 en svt.",
      "⚠ Attention erreur #8 en svt.",
      "⚠ Attention erreur #9 en svt.",
      "⚠ Attention erreur #10 en svt.",
    ],
    cles: [
      "Technique #1 de svt.",
      "Technique #2 de svt.",
      "Technique #3 de svt.",
      "Technique #4 de svt.",
      "Technique #5 de svt.",
      "Technique #6 de svt.",
      "Technique #7 de svt.",
      "Technique #8 de svt.",
      "Technique #9 de svt.",
      "Technique #10 de svt.",
    ],
    autoEval: [
      "Question 1 d'auto-éval sur svt.",
      "Question 2 d'auto-éval sur svt.",
      "Question 3 d'auto-éval sur svt.",
      "Question 4 d'auto-éval sur svt.",
      "Question 5 d'auto-éval sur svt.",
      "Question 6 d'auto-éval sur svt.",
      "Question 7 d'auto-éval sur svt.",
      "Question 8 d'auto-éval sur svt.",
      "Question 9 d'auto-éval sur svt.",
      "Question 10 d'auto-éval sur svt.",
    ],
  },
  general: {
    objectifs: [
      "Objectif general 1: concept approfondi.",
      "Objectif general 2: concept approfondi.",
      "Objectif general 3: concept approfondi.",
      "Objectif general 4: concept approfondi.",
      "Objectif general 5: concept approfondi.",
      "Objectif general 6: concept approfondi.",
      "Objectif general 7: concept approfondi.",
      "Objectif general 8: concept approfondi.",
      "Objectif general 9: concept approfondi.",
      "Objectif general 10: concept approfondi.",
      "Objectif general 11: concept approfondi.",
      "Objectif general 12: concept approfondi.",
      "Objectif general 13: concept approfondi.",
      "Objectif general 14: concept approfondi.",
      "Objectif general 15: concept approfondi.",
      "Objectif general 16: concept approfondi.",
      "Objectif general 17: concept approfondi.",
      "Objectif general 18: concept approfondi.",
      "Objectif general 19: concept approfondi.",
      "Objectif general 20: concept approfondi.",
      "Objectif general 21: concept approfondi.",
      "Objectif general 22: concept approfondi.",
      "Objectif general 23: concept approfondi.",
      "Objectif general 24: concept approfondi.",
      "Objectif general 25: concept approfondi.",
      "Objectif general 26: concept approfondi.",
      "Objectif general 27: concept approfondi.",
      "Objectif general 28: concept approfondi.",
      "Objectif general 29: concept approfondi.",
      "Objectif general 30: concept approfondi.",
    ],
    methodes: [
      "1. Méthode pour general.",
      "2. Méthode pour general.",
      "3. Méthode pour general.",
      "4. Méthode pour general.",
      "5. Méthode pour general.",
      "6. Méthode pour general.",
      "7. Méthode pour general.",
      "8. Méthode pour general.",
      "9. Méthode pour general.",
      "10. Méthode pour general.",
      "11. Méthode pour general.",
      "12. Méthode pour general.",
    ],
    exemples: [
      "Exemple 1 : exercice de general.",
      "Exemple 2 : exercice de general.",
      "Exemple 3 : exercice de general.",
      "Exemple 4 : exercice de general.",
      "Exemple 5 : exercice de general.",
      "Exemple 6 : exercice de general.",
      "Exemple 7 : exercice de general.",
      "Exemple 8 : exercice de general.",
      "Exemple 9 : exercice de general.",
      "Exemple 10 : exercice de general.",
      "Exemple 11 : exercice de general.",
      "Exemple 12 : exercice de general.",
      "Exemple 13 : exercice de general.",
      "Exemple 14 : exercice de general.",
      "Exemple 15 : exercice de general.",
    ],
    pieges: [
      "⚠ Attention erreur #1 en general.",
      "⚠ Attention erreur #2 en general.",
      "⚠ Attention erreur #3 en general.",
      "⚠ Attention erreur #4 en general.",
      "⚠ Attention erreur #5 en general.",
      "⚠ Attention erreur #6 en general.",
      "⚠ Attention erreur #7 en general.",
      "⚠ Attention erreur #8 en general.",
      "⚠ Attention erreur #9 en general.",
      "⚠ Attention erreur #10 en general.",
    ],
    cles: [
      "Technique #1 de general.",
      "Technique #2 de general.",
      "Technique #3 de general.",
      "Technique #4 de general.",
      "Technique #5 de general.",
      "Technique #6 de general.",
      "Technique #7 de general.",
      "Technique #8 de general.",
      "Technique #9 de general.",
      "Technique #10 de general.",
    ],
    autoEval: [
      "Question 1 d'auto-éval sur general.",
      "Question 2 d'auto-éval sur general.",
      "Question 3 d'auto-éval sur general.",
      "Question 4 d'auto-éval sur general.",
      "Question 5 d'auto-éval sur general.",
      "Question 6 d'auto-éval sur general.",
      "Question 7 d'auto-éval sur general.",
      "Question 8 d'auto-éval sur general.",
      "Question 9 d'auto-éval sur general.",
      "Question 10 d'auto-éval sur general.",
    ],
  },
};

export function genererSectionsCours(titre: string, matiere?: string, contenu?: string): SectionCours[] {
  const theme = detecterTheme(titre, matiere);
  const g = GABARITS[theme];
  const sujet = majuscule((titre || "ce chapitre").trim());

  const sections: SectionCours[] = [];

  sections.push({ emoji: "🎯", titre: "Objectifs du chapitre", lignes: g.objectifs });

  sections.push({
    emoji: "🛠️",
    titre: "Méthode pas-à-pas",
    lignes: [`Pour réussir « ${sujet} », suis cette démarche :`, ...g.methodes],
  });

  sections.push({
    emoji: "💡",
    titre: "Exemples d'application",
    lignes: [`Exemples types autour de « ${sujet} » :`, ...g.exemples],
  });

  sections.push({ emoji: "🚫", titre: "Erreurs fréquentes à éviter", lignes: g.pieges });
  sections.push({ emoji: "📌", titre: "Points clés à retenir", lignes: g.cles });
  sections.push({ emoji: "✅", titre: "Questions d'auto-évaluation", lignes: g.autoEval });

  // 📐 Schéma annoté si le chapitre s'y prête
  const schema = schemaPourChapitre(titre);
  if (schema) {
    sections.push({ emoji: "📐", titre: `Schéma : ${schema.titre}`, lignes: [schema.art, "", `➡️ ${schema.legende}`] });
  }

  return sections;
}

/** Concatène toutes les sections en un seul grand texte (utile pour l'audio). */
export function sectionsEnTexte(sections: SectionCours[]): string {
  return sections
    .map((s) => `${s.titre}.\n${s.lignes.join("\n")}`)
    .join("\n\n");
}
