// BANQUE QCM SVT — questions à choix multiples du programme de SVT
// (Seconde → Terminale, programme CEA). 100% hors-ligne.

export interface QcmSvt {
  id: string;
  niveau: 'Seconde' | 'Première' | 'Terminale';
  theme: string;
  question: string;
  options: string[];
  bonneIndex: number; // 0-3
  explication: string;
}

export const QCM_SVT: QcmSvt[] = [
  // --- Seconde : la cellule ---
  { id: 's1', niveau: 'Seconde', theme: 'La cellule', question: 'Quelle structure contrôle toutes les activités de la cellule ?', options: ['La membrane plasmique', 'Le noyau', 'La vacuole', 'Le ribosome'], bonneIndex: 1, explication: 'Le noyau contient l\'ADN, matériel génétique qui dirige les activités cellulaires.' },
  { id: 's2', niveau: 'Seconde', theme: 'La cellule', question: 'Quel organite est le siège de la respiration cellulaire ?', options: ['Le chloroplaste', 'La mitochondrie', 'Le lysosome', 'L\'appareil de Golgi'], bonneIndex: 1, explication: 'La mitochondrie réalise la respiration cellulaire : dégradation du glucose avec consommation d\'O₂ pour produire de l\'ATP.' },
  { id: 's3', niveau: 'Seconde', theme: 'La cellule', question: 'La membrane plasmique est constituée principalement de :', options: ['Protéines et glucides uniquement', 'Bicouche lipidique avec des protéines', 'Cellulose pure', 'Acides nucléiques'], bonneIndex: 1, explication: 'La membrane est un bicouche de phospholipides dans lequel sont insérées des protéines : modèle de la mosaïque fluide.' },
  { id: 's4', niveau: 'Seconde', theme: 'Photosynthèse', question: 'Quel gaz est rejeté lors de la photosynthèse ?', options: ['Le dioxyde de carbone (CO₂)', 'Le dioxygène (O₂)', 'L\'azote (N₂)', 'Le méthane (CH₄)'], bonneIndex: 1, explication: 'La photosynthèse consomme du CO₂ et de l\'eau, et libère du O₂ grâce à l\'énergie lumineuse captée par la chlorophylle.' },
  { id: 's5', niveau: 'Seconde', theme: 'Photosynthèse', question: 'Dans quel organite a lieu la photosynthèse ?', options: ['La mitochondrie', 'Le chloroplaste', 'Le noyau', 'Le ribosome'], bonneIndex: 1, explication: 'Le chloroplaste contient la chlorophylle, pigment qui capture la lumière.' },
  // --- Seconde : géologie ---
  { id: 's6', niveau: 'Seconde', theme: 'Géologie', question: 'La lithosphère est constituée de :', options: ['La croûte terrestre uniquement', 'La croûte et la partie supérieure du manteau', 'Le noyau uniquement', 'Le manteau dans son ensemble'], bonneIndex: 1, explication: 'La lithosphère = croûte (océanique ou continentale) + manteau supérieur rigide, reposant sur l\'asthénosphère ductile.' },
  { id: 's7', niveau: 'Seconde', theme: 'Géologie', question: 'Les séismes sont dus à :', options: ['L\'activité des volcans uniquement', 'La rupture brutale des roches le long d\'une faille', 'La pluie', 'La rotation de la Terre'], bonneIndex: 1, explication: 'L\'accumulation de contraintes provoque la rupture des roches : c\'est le séisme, enregistré par les sismographes.' },
  // --- Première : reproduction ---
  { id: 'p1', niveau: 'Première', theme: 'Reproduction', question: 'Combien de chromosomes possède une cellule somatique humaine ?', options: ['23', '46', '44', '48'], bonneIndex: 1, explication: 'Une cellule somatique humaine possède 46 chromosomes (23 paires), soit 2n = 46 : c\'est le caryotype.' },
  { id: 'p2', niveau: 'Première', theme: 'Reproduction', question: 'La méiose produit des cellules :', options: ['Diploïdes identiques à la cellule mère', 'Haploïdes (n chromosomes) et génétiquement différentes', 'Sans chromosomes', 'Diploïdes et génétiquement différentes'], bonneIndex: 1, explication: 'La méiose réduit le nombre de chromosomes de moitié (2n → n) et assure le brassage génétique : les gamètes sont haploïdes et uniques.' },
  { id: 'p3', niveau: 'Première', theme: 'Reproduction', question: 'Où ont lieu la production et la maturation des spermatozoïdes ?', options: ['Dans les vésicules séminales', 'Dans les testicules (tubes séminifères)', 'Dans la prostate', 'Dans l\'épididyme uniquement'], bonneIndex: 1, explication: 'La spermatogenèse se déroule dans les tubes séminifères des testicules ; les spermatozoïdes achevent leur maturation dans l\'épididyme.' },
  { id: 'p4', niveau: 'Première', theme: 'Génétique', question: 'Un individu de génotype Aa (allèles A dominant, a récessif) présente le phénotype :', options: ['Récessif', 'Dominant [A]', 'Intermédiaire obligatoirement', 'Aucun des deux'], bonneIndex: 1, explication: 'L\'allèle dominant A s\'exprime en présence du récessif : l\'hétérozygote Aa exprime le caractère dominant.' },
  { id: 'p5', niveau: 'Première', theme: 'Génétique', question: 'Deux parents hétérozygotes (Aa × Aa) ont quelle probabilité d\'avoir un enfant aa ?', options: ['0%', '25%', '50%', '75%'], bonneIndex: 1, explication: 'Échiquier de croisement : 1/4 AA, 2/4 Aa, 1/4 aa → 25% de homozygotes récessifs.' },
  // --- Première : immunologie ---
  { id: 'p6', niveau: 'Première', theme: 'Immunologie', question: 'Les anticorps sont produits par :', options: ['Les lymphocytes T cytotoxiques', 'Les plasmocytes (issus des lymphocytes B)', 'Les macrophages', 'Les hématies'], bonneIndex: 1, explication: 'Les lymphocytes B activés se différencient en plasmocytes sécréteurs d\'anticorps spécifiques de l\'antigène.' },
  { id: 'p7', niveau: 'Première', theme: 'Immunologie', question: 'Le VIH détruit principalement :', options: ['Les globules rouges', 'Les lymphocytes T4 (auxiliaires)', 'Les plaquettes', 'Les neurones'], bonneIndex: 1, explication: 'Le VIH infecte et détruit les LT4, chefs d\'orchestre de la réponse immunitaire, ce qui provoque l\'immunodéficience (sida).' },
  // --- Terminale : génétique ---
  { id: 't1', niveau: 'Terminale', theme: 'Génétique', question: 'L\'ADN est constitué de :', options: ['Un simple brin de nucléotides', 'Deux brins en double hélice', 'Trois brins', 'Des acides aminés'], bonneIndex: 1, explication: 'L\'ADN est une double hélice de nucléotides (A, T, G, C) reliés par des liaisons hydrogène : A-T et G-C (complémentarité).' },
  { id: 't2', niveau: 'Terminale', theme: 'Génétique', question: 'La synthèse d\'une protéine à partir de l\'ARNm s\'appelle :', options: ['La transcription', 'La traduction', 'La réplication', 'La mutation'], bonneIndex: 1, explication: 'La traduction a lieu dans le ribosome : chaque codon de l\'ARNm correspond à un acide aminé (code génétique).' },
  { id: 't3', niveau: 'Terminale', theme: 'Génétique', question: 'Un codon est constitué de combien de nucléotides ?', options: ['1', '2', '3', '4'], bonneIndex: 2, explication: 'Le code génétique est un triplet : 3 nucléotides de l\'ARNm codent un acide aminé (64 codons possibles).' },
  { id: 't4', niveau: 'Terminale', theme: 'Neurophysiologie', question: 'Le potentiel d\'action est propagé le long :', options: ['Du corps cellulaire uniquement', 'De l\'axone des neurones', 'Des dendrites uniquement', 'De la gaine de myéline'], bonneIndex: 1, explication: 'Le message nerveux (potentiel d\'action) se propage le long de l\'axone, de façon régénérative et unidirectionnelle.' },
  { id: 't5', niveau: 'Terminale', theme: 'Neurophysiologie', question: 'La synapse neuro-musculaire libère quel neurotransmetteur ?', options: ['La dopamine', 'L\'acétylcholine', 'L\'insuline', 'Le cortisol'], bonneIndex: 1, explication: 'L\'acétylcholine est libérée par les terminaisons motrices et déclenche la contraction musculaire (plaque motrice).' },
  // --- Terminale : évolution / écologie ---
  { id: 't6', niveau: 'Terminale', theme: 'Écologie', question: 'Dans une chaîne alimentaire, les producteurs primaires sont :', options: ['Les herbivores', 'Les végétaux chlorophylliens', 'Les carnivores', 'Les décomposeurs'], bonneIndex: 1, explication: 'Les producteurs primaires (végétaux chlorophylliens) produisent la matière organique à partir de la matière minérale : base de tous les écosystèmes.' },
  { id: 't7', niveau: 'Terminale', theme: 'Écologie', question: 'Que représente une pyramide écologique ?', options: ['Le poids total des individus', 'La répartition de la biomasse/énergie entre les niveaux trophiques', 'Le nombre d\'espèces', 'L\'âge des individus'], bonneIndex: 1, explication: 'La pyramide montre la décroissance de la biomasse et de l\'énergie d\'un niveau trophique à l\'autre (≈ 10% transférés).' },
  { id: 't8', niveau: 'Terminale', theme: 'Évolution', question: 'La sélection naturelle favorise :', options: ['Les individus les plus forts', 'Les individus les mieux adaptés à leur milieu', 'Les plus grands individus', 'Le hasard uniquement'], bonneIndex: 1, explication: 'Darwin : les variations avantageuses dans un milieu donné augmentent la survie et la reproduction : ce sont les mieux adaptés qui se reproduisent le plus.' },
  { id: 't9', niveau: 'Terminale', theme: 'Génétique', question: 'Une mutation est :', options: ['Toujours mortelle', 'Une modification de la séquence d\'ADN, source de diversité génétique', 'Une réaction immunitaire', 'Une division cellulaire'], bonneIndex: 1, explication: 'Les mutations (erreurs de réplication, agents mutagènes) créent de nouveaux allèles : source brute de la biodiversité et de l\'évolution.' },
  { id: 't10', niveau: 'Terminale', theme: 'Immunologie', question: 'Le rôle des lymphocytes T8 cytotoxiques est de :', options: ['Produire des anticorps', 'Détruire les cellules infectées', 'Phagocyter les bactéries', 'Transporter l\'oxygène'], bonneIndex: 1, explication: 'Les LT8 reconnaissent les cellules infectées (via l\'antigène du CMH) et les détruisent par perforation : réponse immunitaire cellulaire.' },

  // --- Lot 2 : banque enrichie ---
  // --- Lot 2 : banque enrichie (accentue) ---
  { id: 's8', niveau: 'Seconde', theme: 'La cellule', question: "La paroi cellulosique se trouve chez :", options: ["Les cellules animales", "Les cellules végétales", "Les bactéries uniquement", "Tous les êtres vivants"], bonneIndex: 1, explication: "La paroi de cellulose rigidifie et protège la cellule végétale." },
  { id: 's9', niveau: 'Seconde', theme: 'Géologie', question: "Les roches volcaniques se forment par :", options: ["Refroidissement lent en profondeur", "Refroidissement rapide en surface", "Dépôt de sédiments", "Métamorphisme"], bonneIndex: 1, explication: "Refroidissement rapide du magma en surface : cristaux invisibles (basalte)." },
  { id: 's10', niveau: 'Seconde', theme: 'Écologie', question: "Les décomposeurs transforment la matière organique morte en :", options: ["Matière organique vivante", "Matière minérale réutilisable", "Énergie lumineuse", "Rien"], bonneIndex: 1, explication: "Ils minéralisent les débris : la matière minérale retourne aux producteurs (cycle de la matière)." },
  { id: 's11', niveau: 'Seconde', theme: 'La cellule', question: "Le cytoplasme est :", options: ["Le noyau de la cellule", "Le liquide interne où baignent les organites", "Une membrane", "Un chromosome"], bonneIndex: 1, explication: "Milieu interne, siège des réactions cellulaires." },
  { id: 'p8', niveau: 'Première', theme: 'Respiration', question: "Le glucose est totalement dégradé en CO₂ et H₂O lors de :", options: ["La fermentation", "La respiration cellulaire", "La photosynthèse", "La digestion"], bonneIndex: 1, explication: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP (mitochondrie)." },
  { id: 'p9', niveau: 'Première', theme: 'Respiration', question: "Sans dioxygène, le muscle pratique :", options: ["La respiration", "La fermentation lactique", "La photosynthèse", "Rien"], bonneIndex: 1, explication: "La fermentation lactique produit du lactate : elle explique les courbatures après l'effort." },
  { id: 'p10', niveau: 'Première', theme: 'Génétique', question: "Les allèles d'un gène sont situés :", options: ["Sur des chromosomes différents", "Au même locus sur les chromosomes homologues", "Sur l'ARN", "Dans le cytoplasme"], bonneIndex: 1, explication: "Un allèle du père et un de la mère, au même locus." },
  { id: 'p11', niveau: 'Première', theme: 'Reproduction', question: "La fécondation rétablit :", options: ["L'haploïdie", "La diploïdie (2n)", "La méiose", "La mitose"], bonneIndex: 1, explication: "n + n = 2n : le zygote redevient diploïde (46 chromosomes chez l'homme)." },
  { id: 'p12', niveau: 'Première', theme: 'Immunologie', question: "Un vaccin provoque :", options: ["Une maladie grave", "Une immunité sans faire la maladie", "Une allergie", "La destruction des globules rouges"], bonneIndex: 1, explication: "Le vaccin entraîne le système immunitaire : mémoire sans maladie." },
  { id: 't11', niveau: 'Terminale', theme: 'Génétique', question: "La réplication de l'ADN est :", options: ["Conservative", "Semi-conservative", "Totalement nouvelle", "Aléatoire"], bonneIndex: 1, explication: "Chaque hélice fille garde un brin parental (Meselson et Stahl)." },
  { id: 't12', niveau: 'Terminale', theme: 'Neurophysiologie', question: "Au repos, l'intérieur du neurone est :", options: ["Positif", "Négatif (environ −70 mV)", "Neutre", "Positif puis négatif"], bonneIndex: 1, explication: "Potentiel de repos −70 mV, maintenu par la pompe Na⁺/K⁺." },
  { id: 't13', niveau: 'Terminale', theme: 'Immunologie', question: "Les macrophages :", options: ["Produisent des anticorps", "Phagocytent les microbes et présentent leurs antigènes", "Détruisent les cellules cancéreuses", "Stockent l'énergie"], bonneIndex: 1, explication: "Ils phagocytent et présentent les antigènes : lanceurs de la réponse immunitaire." },
  { id: 't14', niveau: 'Terminale', theme: 'Écologie', question: "Le rendement énergétique entre deux niveaux trophiques est d'environ :", options: ["90 %", "50 %", "10 %", "1 %"], bonneIndex: 2, explication: "Environ 10 % seulement passe au niveau suivant : d'où les pyramides écologiques." },
  { id: 't15', niveau: 'Terminale', theme: 'Évolution', question: "Deux populations isolées géographiquement forment deux espèces par :", options: ["Dérive génétique", "Spéciation allopatrique", "Sélection sexuelle", "Croisement"], bonneIndex: 1, explication: "Isolement géographique puis isolement reproductif." },
  { id: 't16', niveau: 'Terminale', theme: 'Génétique', question: "Le brin complémentaire de A-T-G-C est :", options: ["T-A-C-G", "A-T-G-C", "G-C-A-T", "C-G-T-A"], bonneIndex: 0, explication: "Complémentarité : A face à T, G face à C. ATGC donne TACG." },
  { id: 't17', niveau: 'Terminale', theme: 'Génétique', question: "La trisomie 21 résulte le plus souvent de :", options: ["Une mutation de gène", "Une non-disjonction chromosomique en méiose", "Un virus", "La mitose"], bonneIndex: 1, explication: "Un gamète reçoit deux chromosomes 21 : le zygote en porte trois (47)." },
];

export function themesSvt(): string[] {
  return Array.from(new Set(QCM_SVT.map((q) => q.theme)));
}
